Devops ci/add license verification pipeline
speedb-io/speedb pull request #106
Opened 2022-08-03 13:30 UTC by nathan-bo

added license verification pipeline and implement to ci

2022-08-16 09:29 UTC, rtpro requested changes

2022-08-16 09:29 UTC, rtpro commented on .github/workflows/license_verify.yml
> +            if ! grep -q "Copyright (C) 2022 Speedb Ltd. All rights reserved." "$file"; then
@nathan-bo Please note that the year should not be part of the grep, as it would change next year.. :)

2022-08-16 11:20 UTC, nathan-bo commented on .github/workflows/license_verify.yml
> +            if ! grep -q "Copyright (C) 2022 Speedb Ltd. All rights reserved." "$file"; then
fixed, now it will use the current year instead of a set string :)

2022-08-21 08:40 UTC, nathan-bo commented on .github/workflows/license_verify.yml
> +            if ! grep -q "Copyright (C) 2022 Speedb Ltd. All rights reserved." "$file"; then
Changed it to regex to look for 20** as the year, let me know if you want this changed

2022-08-22 06:56 UTC, maxb-io commented on .github/workflows/license_verify.yml
> +            if ! grep -q "Copyright (C) 2022 Speedb Ltd. All rights reserved." "$file"; then
@nathan-bo I still see the hardcoded "2022". You can use regex for limiting to year 20XX: 
if ! grep -q "Copyright (C) 20.. Speedb Ltd. All rights reserved." "$file"; then
or catch the current year:
 grep -q  "Copyright (C) `date +%Y` Speedb Ltd. All rights reserved." 
 grep -q  "Copyright (C) $(date +%Y) Speedb Ltd. All rights reserved."

2023-05-24 07:01 UTC, closed without merging