Update license files to comply with Apache 2.0
speedb-io/speedb pull request #111
Opened 2022-08-04 11:21 UTC by rtpro

2022-08-04 11:21 UTC, rtpro commented
@isaac-io Please review this PR.

2022-08-04 11:50 UTC, isaac-io approved these changes

2022-08-04 11:50 UTC, isaac-io requested changes

2022-08-04 11:50 UTC, isaac-io commented on AUTHORS
> +# Speedb
This is not a Markdown file. I think we can just remove this line.

2022-08-04 12:50 UTC, rtpro commented
Depends on PR #103 
We need to remove GPL based dependency gnu_parallel - PR #103

2022-08-09 11:27 UTC, isaac-io commented
I opened #119 for the removal of the GPL.

2022-08-25 15:42 UTC, merged