Import shorten memtable switch latency #14
speedb-io/speedb pull request #131
Opened 2022-08-23 06:52 UTC by ayulas

2022-08-24 10:08 UTC, isaac-io requested changes

2022-08-24 10:08 UTC, isaac-io commented on plugin/speedb/memtable/hash_spd_rep.cc
> +      std::make_shared<SortVectorContainer>(compare, add_list_limit_size_);
Can we instead change `SortVectorContainer` to not get the comparator in the constructor and pass it to the relevant functions that need it as done in the bucket functions? This allows avoiding having to save `add_list_limit_size_` as a member, and reduces code duplication (because `PostCreate()` will only need to set the allocator). Note that it would require make `compare_` a pointer, so that it could be set outside a constructor in `PostCreate()`.

2022-08-24 10:08 UTC, isaac-io commented on plugin/speedb/memtable/hash_spd_rep.cc
> +    // Construct new memtable only for the heavy object initilized proposed
This comment seems out of place.

2022-08-24 10:08 UTC, isaac-io commented on plugin/speedb/memtable/hash_spd_rep.h
> +  ~HashSpdRepFactory();
Why is this not marked `override`?

2022-08-24 10:08 UTC, isaac-io commented on plugin/speedb/memtable/hash_spd_rep.h
> +#include "rocksdb/comparator.h"
Why is this include needed?

2022-08-24 11:16 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +      std::make_shared<SortVectorContainer>(compare, add_list_limit_size_);
not sure i follow. making the compare as a pointer is problematic

2022-08-24 11:31 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.h
> +#include "rocksdb/comparator.h"
removed

2022-08-24 11:31 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.h
> +  ~HashSpdRepFactory();
done

2022-08-24 11:31 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +    // Construct new memtable only for the heavy object initilized proposed
done

2022-08-24 11:31 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +      add_list_limit_size_(add_list_limit_size) {
done

2022-08-24 11:51 UTC, ayulas commented
pls review f3a7b17f3551b2a0e52c1a430ea0449e28a79329

2022-08-24 12:33 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +      std::make_shared<SortVectorContainer>(compare, add_list_limit_size_);
sorry it is not in one place . for example the sortthread call void SortVectorContainer::AdvanceAndSort which needs the comparator which currently in SortVectorContainer. i think that to keep it as it now...
pls review

2022-08-24 12:34 UTC, ayulas commented
pls review

2022-08-24 12:37 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +      std::make_shared<SortVectorContainer>(compare, add_list_limit_size_);
just mention that in the updated code the comparator is only a member of the sort vector..

2022-08-25 14:01 UTC, isaac-io requested changes
I left a couple of comments (sorry for not noticing them earlier). Other than those, LGTM.

2022-08-28 08:44 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.h
> +  bool terminate_switch_memtable_;
done

2022-08-28 08:44 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +    ;
done

2022-08-28 08:55 UTC, isaac-io approved these changes
LGTM. Please rebase on `main`.

2022-10-02 12:33 UTC, Yuval-Ariel commented
@ayulas , check sources fails on:
https://github.com/speedb-io/speedb/actions/runs/3168558728/jobs/5159839033#step:14:17 
```
build_tools/check-sources.sh
plugin/speedb/memtable/hash_spd_rep.cc:using namespace stl_wrappers;
make: *** [Makefile:1221: check-sources] Error 1
^^^^ Do not use "using namespace"
```

2022-10-03 05:58 UTC, Yuval-Ariel commented
QA passed on 63ee520058f53d406a3ac8ec46c673a44df09c38

2022-11-14 09:09 UTC, Guyme commented
Switch functionality was added to ticket https://github.com/speedb-io/speedb/issues/98 PR https://github.com/speedb-io/speedb/pull/188 https://github.com/speedb-io/speedb/commit/7e5e7bc04bb8813f4bea66dc6030074b4b2658c3

2022-11-14 09:09 UTC, closed without merging