Accurate memory tracking of immutable memory
speedb-io/speedb pull request #132
Opened 2022-08-23 09:46 UTC by udi-speedb

2022-08-23 19:54 UTC, isaac-io requested changes

2022-08-23 19:54 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +    ReserveMemWithCache(curr_mem_used + mem);
This is an unsafe change. Consider the following scenario with two threads, T1 and T2:

1. T1 Calls `ReserveMem(5)` and gets `curr_mem_used = 0`.
2. T2 Calls `ReserveMem(7)` and gets `curr_mem_used = 5`.
3. T2 Calls `ReserveMemWithCache(12)` (5 + 7).
4. T1 Calls `ReserveMemWithCache(5)` (0 + 5).

That's why the original code does the increment of used memory under mutex, in order to ensure that the cache gets a correct reservation, and the atomic increment was used only if cache reservation isn't configured.

2022-08-23 19:54 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +  memory_inactive_.fetch_add(mem, std::memory_order_relaxed);
This should only be done if enabled. No point in doing unnecessary atomic RMW operations.

2022-08-23 19:54 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +  memory_being_freed_.fetch_add(mem, std::memory_order_relaxed);
Same here: only do this if `enabled()`.

2022-08-23 19:54 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +  memory_being_freed_.fetch_sub(mem, std::memory_order_relaxed);
This assertion is unsafe. You should be doing something along the following lines:

```c++
    const size_t being_freed_before = memory_being_freed_.fetch_sub(mem, std::memory_order_relaxed);
    if (being_freed_before < mem) {
      assert(false);
    }
```

`assert(false)` is used (rather than `assert(being_freed_before >= mem)`) in order to avoid unused variable diagnostic in release builds.

2022-08-23 19:54 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +  assert(memory_being_freed_.load(std::memory_order_relaxed) >= mem);
Same here: asserting on atomic variables before doing the modification is unsafe.

2022-08-23 19:54 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +  memory_being_freed_.fetch_sub(mem, std::memory_order_relaxed);
Same as above: no point in doing atomic RMW if not `enabled()`.

2022-08-23 19:54 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +    FreeMemWithCache(curr_mem_used - mem);
This change is unsafe, as explained above. With cache reservation enabled we should only be changing the used memory under the cache reservation mutex.

2022-08-24 09:44 UTC, isaac-io reviewed
I left a few minor comments, but other than that LGTM. Can you also add a test or two to ensure the new functionality doesn't regress in the future?

2022-08-24 09:44 UTC, isaac-io commented on include/rocksdb/write_buffer_manager.h
> +  // Returns the total memory used by active memtables.
This comment refers to the wrong memory category.

2022-08-24 09:44 UTC, isaac-io commented on include/rocksdb/write_buffer_manager.h
> +  // wraparound
This seems like an upstream bug, regardless of the changes in this PR. Can we open a separate issue to fix this (i.e. track memory state even when disabled in order to avoid this scenario) and make this PR depend on it?

2022-08-24 09:44 UTC, isaac-io commented on memtable/alloc_tracker.cc
> +
This check is redundant. The code below already checks for `!freed_` to avoid freeing when not needed.

2022-08-24 12:45 UTC, udi-speedb commented on memtable/alloc_tracker.cc
> +
If FreeMem() is called twice without this check, the second time it will call FreeMemBegin(), potentially assert(!freed), and do a bunch of unneeded stuff.

2022-08-24 13:08 UTC, isaac-io commented on memtable/alloc_tracker.cc
> +
I see. Can we rename `is_memory_being_freed_` to `memory_free_started_` and change the semantics so that it's not reset below? (only `FreeMemAborted()` should be the one to reset it)

Alternatively, since this is simply a state machine, we can replace all of these members with a single `state_` member of type `AllocTrackerState` which would be defined in the following way:

```c++
enum class AllocTrackerState {
  kAllocating,
  kDoneAllocating,
  kFreeMemStarted,
  kFreed,
};
```

That way `ReserveMem()` could assert that it's in `kAllocating`, `DoneAllocating()` should assert the same and change the state to `kDoneAllocating`, `FreeMemBegin()` would assert that the state is `kDoneAllocating` and set it to `kFreeMemStarted`, and `FreeMemAborted` can assert that the state is `kFreeMemStarted` and revert it back to `kDoneAllocating`.

Then `FreeMem()` could be defined as follows:

```c++
switch (state_) {
case AllocTrackerState::kAllocating:
  DoneAllocating();
  FALLTHROUGH_INTENDED;
case AllocTrackerState::kDoneAllocating:
  FreeMemBegin();
  FALLTHROUGH_INTENDED;
case AllocTrackerState::kFreeMemStarted:
  ...
  state_ = AllocTrackerState::kFreed;
  FALLTHROUGH_INTENDED;
case AllocTrackerState::kFreed:
  break;
default:
  assert(false);
}
```

2022-08-24 13:30 UTC, udi-speedb commented on include/rocksdb/write_buffer_manager.h
> +  // wraparound
I have opened [https://github.com/speedb-io/speedb/issues/138](url)
How do we make a PR depend on it and what does it mean practically?

2022-08-24 13:54 UTC, isaac-io commented on include/rocksdb/write_buffer_manager.h
> +  // wraparound
Thanks!
We currently have no means of specifying that a PR depends on an issue or another PR because the automation is still a WIP, so generally making something dependent on another is currently simply adding `Depends on ...` to the PR description and avoiding merging it until the other one is resolved. My thinking was that since that's an upstream bug, it would be easier if we fixed it before making the changes in this PR, so that it'd be easier to upstream. However, thinking about it some more, I don't think that the failure case justifies holding back this PR if you won't have time to open a PR for the other issue and add a regression test.

2022-08-24 18:11 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +void WriteBufferManager::FreeMemStarted(size_t mem) {
Why the change in naming style here? `FreeMemBegin()` was following the imperative style of `ReserveMem()` and `ScheduleFreeMem()`, as well as `FreeMem()`. Changing this to `FreeMemStarted()` makes it unnecessarily different.

2022-08-24 18:11 UTC, isaac-io commented on memtable/alloc_tracker.cc
> +  bytes_allocated_ = 0U;
Do we really need to reset this considering the fact that it's not exposed anywhere? The state machine should work regardless of its value (and it may actually be nice to have that number if we end up wanting to know in the future how much memory was allocated, even after it was freed, for statistics etc.).

2022-08-24 18:11 UTC, isaac-io commented on memtable/alloc_tracker.cc
> +  state_ = State::kAllocating;
The AllocTracker starts its life under the allocator and `Allocate()` is called many times. What does the `kNone` state signify to warrant the additional checks and reassignment over and over again?

Also, note that you're resetting the state machine to the allocating state even if the assertion doesn't hold. Since you're checking it anyway (so there's no additional cost to doing it only if the state is the expected one), I'm not sure that it's the right thing to do (the same goes for the rest of the state changes below).

2022-08-24 18:58 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +void WriteBufferManager::FreeMemStarted(size_t mem) {
The alloc_tracker is not actually freeing the memory, it is notified of the fact that memory is being freed (more like DoneAllocating). Having said that, both are fine IMO.

2022-08-25 06:57 UTC, isaac-io commented on memtable/write_buffer_manager.cc
> +void WriteBufferManager::FreeMemStarted(size_t mem) {
That's why I only commented about the change in the WBM and not in the AllocTracker. As for `FreeMemBegin()` vs. `BeginFreeMem()`, I'm fine with either.

2022-08-25 07:26 UTC, isaac-io commented on db/memtable_list.cc
> +      m->SetFlushCompleted(false);
I'm only now noticing that you changed the order of these two lines. Is that because we're depending on the value provided to us in `SetFlushCompleted()`? If so, we could make sure that it's different than `flush_completed_` as well before we take action.

2022-08-25 07:26 UTC, isaac-io commented on db/memtable_list.cc
> +        m->SetFlushCompleted(false);
Same here: why the ordering change?

2022-08-25 07:26 UTC, isaac-io commented on db/memtable_list_test.cc
> +      ASSERT_TRUE(!wbm_enabled ||
Can we put it inside an if statement rather than wrapping it in `ASSERT_TRUE`? in case of failure it'll be hard to understand what the expected vs. actual was.

2022-08-25 07:26 UTC, isaac-io commented on db/memtable_list_test.cc
> +        ASSERT_TRUE(!wbm_enabled ||
Same here: please use `ASSERT_GT` in an if rather than `ASSERT_TRUE` so that it'll be easier to understand the expected vs. actual in case of failure.

2022-08-25 07:26 UTC, isaac-io commented on db/memtable_list_test.cc
> +  ASSERT_EQ(wb.mutable_memtable_memory_usage(), expected_used);
Shouldn't `expected_used` be named `expected_mutable`?

2022-08-25 08:05 UTC, udi-speedb commented on db/memtable_list.cc
> +      m->SetFlushCompleted(false);
The original code just set 2 boolean flags without any side effects so the order wasn't at all important.
SetFlushInProgress() / SetFlushCompleted() are now calling alloc tracker's code which uses the state machine and needs the calls in a spceific order.
I don't really understand your point or the reason for it

2022-08-25 10:50 UTC, isaac-io reviewed
Sorry for the small bursts of comments. Only 2 minor comments this time, and hopefully it'll be the last round.

2022-08-25 10:50 UTC, isaac-io commented on db/memtable_list.cc
> +      m->SetFlushCompleted(false);
It doesn't change the behaviour. What I mean is that the original code did it in that order to signify a rollback because `RemoveMemTablesOrRestoreFlags()` is called in `TryInstallMemtableFlushResults()` after `SetFlushCompleted(true)` was called. I'm assuming that you changed the order because of the way the check in `SetFlushCompleted()` relies on `flush_in_progress_` being set to `true` in order to avoid calling abort twice (and the only reason this works is because `flush_is_progress_` is never set to `false` in the good path, when a rollback isn't required). Ideally there wouldn't be two flags, but only a single state machine, but in the current state of things I simply think that the check there should not rely on that but on the value of `flush_completed_` for signifying abort, though I admit that it doesn't change the behaviour, and it was simply a question of regarding the logical ordering of things.

2022-08-25 10:50 UTC, isaac-io commented on db/memtable.h
> +      // In case flush is aborted, notify the memory tracker
Comment in the wrong place. Can you move it inside the `else` branch?

2022-08-25 10:50 UTC, isaac-io commented on db/memtable.h
> +    if (in_progress && (flush_in_progress_ == false)) {
Can we simplify the check by wrapping this in `if (in_progress != flush_in_progress_)`, so that inside we'll only need to check if the new value is `true` or not? It took me a couple of reads to understand that this is basically what the checks are all about.

2022-09-04 12:16 UTC, udi-speedb commented on db/memtable_list.cc
> +      m->SetFlushCompleted(false);
So, should I leave it as is or would you like me to change anything?

2022-09-04 12:16 UTC, udi-speedb commented on db/memtable_list.cc
> +        m->SetFlushCompleted(false);
Same question here

2022-09-04 12:44 UTC, isaac-io commented on db/memtable_list.cc
> +      m->SetFlushCompleted(false);
While I understand that the order doesn't really matter even if some future programmer fumbles and causes abort to be called twice (since the `AllocTracker` protects against that), I still think that the reordering is unnecessary and creates unneeded confusion for readers of this diff. Additionally, it would still be better IMO if the check in `SetFlushCompleted()` relied on `flush_completed_` rather than `flush_in_progress_` (the current state, where it relies on `flush_in_progress_`, is confusing because `SetFlushCompleted()` sets the former, but not the latter). Also, it would be clearer if `SetFlushInProgress()` made sure that `flush_completed_` is `false` before calling abort.

2022-09-06 05:15 UTC, udi-speedb commented
@isaac-io - Please review the last commit. Thanks

2022-09-06 10:16 UTC, isaac-io approved these changes
LGTM.

2022-09-06 11:20 UTC, udi-speedb commented
I have squashed and pushed the branch

2022-09-28 12:50 UTC, merged