Devops ci/move fuzz to reusable workflow
speedb-io/speedb pull request #133
Opened 2022-08-23 10:40 UTC by nathan-bo

2022-09-04 08:03 UTC, isaac-io requested changes

2022-09-04 08:03 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +           tail -20 $GITHUB_WORKSPACE/out/${{ matrix.name }}.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "${{ matrix.name }} failed!"
This will not actually fail the fuzz test. You need a command that doesn't return 0. I suggest adding `&& false` at the end of the line here.

2022-09-04 08:03 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/
How are we going to differentiate between runs if you don't give the file a name that includes the git hash?

2022-09-04 08:03 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
>             bash -xv prepfuz.sh
Why not simply run the commands instead of outputting them to a file and executing it?

2022-09-04 12:28 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/
I can add it back no problem, do you want me to?

2022-09-04 12:30 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
>             bash -xv prepfuz.sh
This is the way it was ran in gitlab ci, I think @maxb-io explained it to me but I can't really remember

2022-09-04 12:31 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +          echo "nameserver 8.8.8.8" > /etc/resolv.conf
done

2022-09-04 12:31 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +           tail -20 $GITHUB_WORKSPACE/out/${{ matrix.name }}.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "${{ matrix.name }} failed!"
fixed, it stayed from tests

2022-09-04 12:47 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/
Please do. There's no need to add it to the file name everywhere, only here when uploading to S3.

2022-09-04 12:51 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +           tail -20 $GITHUB_WORKSPACE/out/${{ matrix.name }}.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "${{ matrix.name }} failed!" && false
Note that due to operator precedence in shell you need to group the last two commands, otherwise the `&&` part would apply regardless of the actual result:

```suggestion
tail -20 $GITHUB_WORKSPACE/out/${{ matrix.name }}.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || { echo "${{ matrix.name }} failed!" && false; }
```

2022-09-04 13:01 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +           tail -20 $GITHUB_WORKSPACE/out/${{ matrix.name }}.log | grep "==AddressSanitizer. Thread limit (4194304 threads) exceeded\. Dying\." || echo "${{ matrix.name }} failed!" && false
done

2022-09-04 13:07 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/
done

2022-09-04 14:40 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/
What you did here wouldn't actually work, because the file isn't created with the hash. What you need is something like the following:

```bash
          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/$GITHUB_SHA-${{ matrix.name }}.log
```

2022-09-04 23:24 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/
changed it, runs properly now

2022-09-05 06:36 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
>    fuzzer_sum:
I'm not sure about the role of this flow. Since the check for fuzzer failure is already done inside the fuzzing workflow, this flow will only be executed on a successful path, which is a waste.

2022-09-05 06:36 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/$GITHUB_SHA-${{ matrix.name }}.log
What's the use of uploading the logs to S3 after the fuzzer has already succeeded? I case of failure this job will not be executed anyway (because the previous job would fail), and in a successful run we have no use for the logs.

2022-09-05 08:25 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/$GITHUB_SHA-${{ matrix.name }}.log
I was told we want to save the logs, is this not correct? I can remove it if there's no use

2022-09-05 08:52 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
>    fuzzer_sum:
we could change it if needed

2022-09-05 08:52 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/$GITHUB_SHA-${{ matrix.name }}.log
The job later removes them, so they are not saved anyway. What we need is a way to store the logs on failure, not on success.

2022-09-05 08:57 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/$GITHUB_SHA-${{ matrix.name }}.log
the clean is only for testing, so that it will automatically clean itself instead of manually doing it. I'll change it to save only when the job fails

2022-09-05 09:24 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
>    fuzzer_sum:
Let's remove it then. No reason to do redundant work.

2022-09-05 12:56 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +          aws s3 cp $GITHUB_WORKSPACE/out/${{ matrix.name }}.log s3://spdb-github-ci/$GITHUB_SHA-${{ matrix.name }}.log
made the change, let me know if you want it different

2022-09-05 13:09 UTC, isaac-io requested changes

2022-09-05 13:09 UTC, isaac-io commented on .github/workflows/test_fuzz.yml
> +        if: steps.${{ matrix.name }}.outcome != 'success'
This will run on cancellation, which we don't really want. You should probably only run this on failure.

2022-09-05 13:09 UTC, isaac-io commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/test_fuzz.yml@main
Let's use the [local repository syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow) without pinning to `main`.

2022-09-05 13:25 UTC, nathan-bo commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/test_fuzz.yml@main
done

2022-09-05 13:46 UTC, nathan-bo commented on .github/workflows/test_fuzz.yml
> +        if: steps.${{ matrix.name }}.outcome != 'success'
changed it to run explicitly if the outcome is 'failure'

2022-09-05 13:51 UTC, isaac-io approved these changes

2022-09-05 13:52 UTC, merged