Devops ci/move build to reusable workflow
speedb-io/speedb pull request #139
Opened 2022-08-25 11:01 UTC by nathan-bo

2022-08-25 11:15 UTC, isaac-io requested changes

2022-08-25 11:15 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +        key: ${{runner.os}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
Why are we adding a timestamp to the cache key? That makes it so it'll never be hit in later runs. We should use something else (such as the matrix name, as was in the old CI on GitLab).

2022-08-25 11:15 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +          cat ~/.ccache/ccache.txt
Why are these needed?

2022-08-25 11:15 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +          echo >&2 "error: the build directory should not exist" && false NIK
What's with the `NIK` at the end here?

2022-08-25 11:15 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +          echo "Already exists"
If this print is needed, can we make it more meaningful? If it's a leftover from debugging the workflow, let's remove it.

2022-08-25 11:15 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +        df -h
Why are these done? (also note that printing the environment variables is dangerous. It may expose secrets)

2022-08-25 11:15 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +        echo "nameserver 8.8.8.8" > /etc/resolv.conf
This should probably be one line up, before `apk add git`.

2022-08-25 11:15 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +
Since this workflow doesn't change the repository, can we explicitly set its permissions to `read`?

2022-08-30 08:06 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        key: ${{runner.os}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
In general this is how GitHub  uses cache on their side, you need the key to be unique and the cache hits if a part of the key matches

2022-08-30 08:07 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +          echo >&2 "error: the build directory should not exist" && false NIK
This is what we had on gitlab, I'll change it if it's not needed

2022-08-30 08:13 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +
by default github actions has read permissions as specified here:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

2022-08-30 08:26 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +          echo "Already exists"
I'll make it more meaningful, no problem

2022-08-30 08:26 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        df -h
I'll remove printing of the environment variables

2022-08-30 08:26 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        echo "nameserver 8.8.8.8" > /etc/resolv.conf
Will change

2022-08-30 08:40 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +        key: ${{runner.os}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
That's not what the documentation of the `cache` action says. If no exact match is found for either `key` or `restore-keys`, a new cache is created. See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action

2022-08-30 08:42 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +
The table you linked to actually says that by default actions have read/write permission with the `GITHUB_TOKEN`.

2022-08-30 08:45 UTC, isaac-io requested changes

2022-08-30 08:45 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +        rm -rf /usr/share/dotnet || echo ""
What's this line for? We don't have dotnet installed in the container anyway.

2022-08-30 08:45 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +          echo >&2 "error: the build directory should not exist" && false NIK
I was asking specifically about the `NIK` part there. That didn't exist in GitLab.

2022-08-30 13:04 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        rm -rf /usr/share/dotnet || echo ""
Just checked to make sure again, it is taken from Gitlab CI

<img width="570" alt="Screen Shot 2022-08-30 at 16 03 00" src="https://user-images.githubusercontent.com/103655431/187443936-675b402d-f918-4adf-bee5-4b59956eda34.png">

2022-08-30 13:32 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        rm -rf /usr/share/dotnet || echo ""
It's left over from one of my tests, removed it

2022-08-30 14:12 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +          echo >&2 "error: the build directory should not exist" && false NIK
it shouldn't be there, removed it

2022-08-31 12:08 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        key: ${{runner.os}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
The main problem with not using the timestamps is that you can only use specific cache once for some reason (I can say for sure after testing this as you can see here: https://github.com/speedb-io/speedb/runs/8108257100?check_suite_focus=true
so when you use the timestamp it will get one of the caches that were saved (which doesn't matter since they're all the same) and then lets you use 3 in parallel as you can see here: https://github.com/speedb-io/speedb/actions/runs/2963621327

2022-08-31 12:27 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +
after testing, there's no need for any write permissions and I changed it to read-all

2022-09-04 07:56 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +
Do we really need `read-all`, or can we restrict to `contents: read`?

2022-09-04 08:01 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        key: ${{runner.os}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
I could maybe use a hybrid of the 2, both ${{matrix.name}} and the timestamp so that there could be more than 1 caches available (in case a few jobs run simultaneously they will be able to use the cache) and they will always use the correct cache and not something random

2022-09-04 08:07 UTC, isaac-io commented on .github/workflows/full-builds.yml
> +        key: ${{runner.os}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
Can you provide an example of where jobs can't use the same cache simultaneously? I'm not sure that I understand why you think such a limitation exists.

2022-09-04 09:52 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +        key: ${{runner.os}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
I dont have the old log files but after changing cache v2 to v3 and testing I can't reproduce it. I'll implement the changes and ask for another review

2022-09-04 11:58 UTC, nathan-bo commented on .github/workflows/full-builds.yml
> +
sure, done

2022-09-04 12:31 UTC, isaac-io commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/full-builds.yml@devops-ci/move_build_to_reusable_workflow
This should probably not be pinned to `devops-ci/move_build_to_reusable_workflow`.

2022-09-04 19:37 UTC, nathan-bo commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/full-builds.yml@devops-ci/move_build_to_reusable_workflow
yes, this was only to use a different workflow to test. fixed

2022-09-05 06:30 UTC, isaac-io commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/full-builds.yml@devops-ci/move_build_to_reusable_workflow
Is there a reason not to use the local repository syntax mentioned there? (i.e. `./.github/workflows/full-builds.yml`)

Unless we want to avoid running workflows from the current branch, I see no reason to pin or use the full path.

2022-09-05 08:53 UTC, nathan-bo commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/full-builds.yml@devops-ci/move_build_to_reusable_workflow
we could use it either way, let me know if you want it changed

2022-09-05 08:56 UTC, isaac-io commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/full-builds.yml@devops-ci/move_build_to_reusable_workflow
If there's no reason to pin, let's use the local repository syntax without pinning.

2022-09-05 09:59 UTC, nathan-bo commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/full-builds.yml@devops-ci/move_build_to_reusable_workflow
done

2022-09-05 11:23 UTC, isaac-io approved these changes

2022-09-05 11:29 UTC, isaac-io requested changes
Note: CI pipeline fails with:

```
Invalid workflow file:
                        .github/workflows/ci_pipeline.yml#L15
The workflow is not valid. 
.github/workflows/ci_pipeline.yml (Line: 15, Col: 3): The workflow must  contain at least one job with no dependencies.
```

https://github.com/speedb-io/speedb/actions/runs/2992824504

2022-09-05 11:40 UTC, nathan-bo commented
> Note: CI pipeline fails with:
> 
> ```
> Invalid workflow file:
>                         .github/workflows/ci_pipeline.yml#L15
> The workflow is not valid. 
> .github/workflows/ci_pipeline.yml (Line: 15, Col: 3): The workflow must  contain at least one job with no dependencies.
> ```
> 
> https://github.com/speedb-io/speedb/actions/runs/2992824504

yes, it makes sense since the file which contains the the workflow doesn't exist on main yet since it wasn't pushed

2022-09-05 11:53 UTC, isaac-io commented
No, that's not the issue. If you look at the [full CI pipeline file in this PR](https://github.com/speedb-io/speedb/blob/7dfc22019e0a1a0f57d83102b6ebb304977eb7f7/.github/workflows/ci_pipeline.yml) you can immediately see that all of the jobs depend on other jobs (specifically, this PR changes it so that build depends on Sanity, which isn't defined). This prevents a workflow from beginning.

2022-09-05 12:11 UTC, nathan-bo commented
> No, that's not the issue. If you look at the [full CI pipeline file in this PR](https://github.com/speedb-io/speedb/blob/7dfc22019e0a1a0f57d83102b6ebb304977eb7f7/.github/workflows/ci_pipeline.yml) you can immediately see that all of the jobs depend on other jobs (specifically, this PR changes it so that build depends on Sanity, which isn't defined). This prevents a workflow from beginning.

Sorry, I was looking at something else.
https://github.com/speedb-io/speedb/pull/84 we will have to approve and push this PR in order for it to be solved (the implementation of sanity to CI)

2022-11-16 09:21 UTC, closed without merging