hash spd bucket get - use key without timestamp
speedb-io/speedb pull request #142
Opened 2022-08-28 09:48 UTC by ayulas

2022-08-28 10:12 UTC, isaac-io requested changes

2022-08-28 10:12 UTC, isaac-io commented on plugin/speedb/memtable/hash_spd_rep.cc
> +    auto key_comparator = static_cast<const MemTable::KeyComparator*>(&compare);
Can we use `dynamic_cast` and assert here if `ROCKSDB_USE_RTTI` is set and `NDEBUG` isn't, just to be on the safe side?

```suggestion
#if defined(ROCKSDB_USE_RTTI) && !defined(NDEBUG)
    auto key_comparator = dynamic_cast<const MemTable::KeyComparator*>(&compare);
    assert(key_comparator != nullptr);
#else
    auto key_comparator = static_cast<const MemTable::KeyComparator*>(&compare);
#endif
```

2022-08-28 10:12 UTC, isaac-io commented on plugin/speedb/memtable/hash_spd_rep.cc
>    }
Can we inline this in the version that accepts a `char*`, seeing as no API in this file needs to pass an internal key? (the change from memtable key to internal key in line 954 would be unnecessary then)

2022-08-28 10:26 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +    auto key_comparator = static_cast<const MemTable::KeyComparator*>(&compare);
done

2022-08-28 10:26 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
>    }
done

2022-08-28 10:30 UTC, isaac-io approved these changes
LGTM.

2022-10-02 09:07 UTC, closed without merging

2022-10-02 09:08 UTC, ayulas commented
this. code is the not updated code of hash_spd
this should be ignore and new pull request will be assign to spdb memtable