#34: Set purges priority to low instead of high
speedb-io/speedb pull request #151
Opened 2022-09-06 12:26 UTC by AmnonHanuhov

2022-09-07 10:56 UTC, isaac-io requested changes

2022-09-07 10:56 UTC, isaac-io commented on db/db_test2.cc
> +  ASSERT_EQ(value, base_value);
That's the wrong fix. The test tries to take up a slot in the high priority pool in order to prevent a purge from running when the iterator is deleted. Now that purges are running in the low priority pool, the low pool is available, and purges have a chance to run. Please change the test so that it still blocks the purge that's now scheduled in the low priority pool.

2022-09-07 11:12 UTC, isaac-io commented
Additionally, when running `make check` locally I see the following failure very early on:

```
[ RUN      ] DeleteFileTest.BackgroundPurgeIteratorTest
db/deletefile_test.cc:124: Failure
Expected equality of these values:
  required_sst
    Which is: 1
  sst_cnt
    Which is: 3
terminate called after throwing an instance of 'testing::internal::GoogleTestFailureException'
  what():  db/deletefile_test.cc:124: Failure
Expected equality of these values:
  required_sst
    Which is: 1
  sst_cnt
    Which is: 3
```

Can you look into it and make sure that no other tests are failing?

2022-09-13 08:02 UTC, isaac-io approved these changes

2022-09-13 08:07 UTC, Yuval-Ariel approved these changes

2022-09-13 08:11 UTC, isaac-io commented on db/db_test2.cc
> +  ASSERT_EQ(value, base_value);
You're looking at an old diff.

2022-09-13 08:14 UTC, Yuval-Ariel commented on db/db_test2.cc
> +  ASSERT_EQ(value, base_value);
the comment must have remained from last review..

2022-09-13 08:16 UTC, Yuval-Ariel commented
in any case, i approved as well to start the CI. seems broken atm so i started it manually - https://github.com/speedb-io/speedb/actions/runs/3043385506

2022-09-28 10:04 UTC, merged