db_bench: Enhancement - Support multiple benchmarks groups, each with its own config (#220)
speedb-io/speedb pull request #250
Opened 2022-11-17 06:00 UTC by udi-speedb

2022-11-17 11:23 UTC, Yuval-Ariel requested changes

2022-11-17 11:23 UTC, Yuval-Ariel commented on tools/db_bench_tool.cc
> +void RecordFirstGroupApplicableFlags() {
why are only these flags recorded and checked? where are they later used which could cause a problem?

2022-11-17 11:23 UTC, Yuval-Ariel commented on tools/db_bench_tool.cc
> +void RecordFirstGroupApplicableFlags() {
for example, the FLAGS_env_uri is only used for the first group in ValidateAndProcessEnvFlags so i dont see a reason to call ValidateSubsequentGroupsDoNotOverrideApplicableFlags on it.

2022-11-17 11:24 UTC, Yuval-Ariel commented on tools/db_bench_tool.cc
> +// gflags help (generated automatically)
can you rephrase this so its a bit more clear?

2022-11-20 09:20 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +// ROCKSDB_LITE' macros
OK. I will open a separate issue for this.

2022-11-20 09:23 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +//
OK. I will take applicable parts and duplicate in the help section

2022-11-20 09:26 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +//     subsequent groups are silently ignored.
Verifying that all of the options have remained as is is too complex (there are tons of options and comparing them is complicated).
I will emphasize in the help message that overriding them  in groups > 1 is SILENTLY ignored

2022-11-20 11:18 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +// ROCKSDB_LITE' macros
@Yuval-Ariel I have opened [https://github.com/speedb-io/speedb/issues/256](url)
Will remove my comment

2022-11-20 11:21 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +void RecordFirstGroupApplicableFlags() {
I have explicitly checked those flags that I am ignoring in groups > 1.

2022-11-20 11:23 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +// gflags help (generated automatically)
Done

2022-11-20 11:53 UTC, udi-speedb commented
@Yuval-Ariel - I have pushed a commit with the CR updates we have discussed.
Coming next are additional changes that I accidentally performed on #221 but belong here.

2022-11-20 13:05 UTC, Yuval-Ariel commented on tools/db_bench_tool.cc
> +    groups, "",
i dont see an instruction to put the -groups flags in the first place after ./db_bench (2nd arg total) here and its definitely mandatory. it is in the Synthax part but i think a more clear instruction to place the flag in the 2nd position is required.

2022-11-20 13:05 UTC, Yuval-Ariel commented on tools/db_bench_tool.cc
> +//     fres db in groups > 1
*fresh

2022-11-20 14:35 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +//    specified benchmarks and exiting. This is the DEFULT mode.
Yes. Fixed

2022-11-20 14:36 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +    "supported flags). "
The group's configuration is dictated by the values of its supported flags.
Please propose a clarification / rephrasing

2022-11-20 14:37 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +    groups, "",
Added.

2022-11-20 14:43 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +    "supported flags). "
Removed the sentence in parenthesis since it's confusing

2022-11-20 14:49 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +//     fres db in groups > 1
Fixed

2022-11-20 14:51 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +    "for all subsequent groups. Subsequent groups may override the "
I have reformatted.

2022-11-20 19:10 UTC, Yuval-Ariel approved these changes

2022-11-21 04:58 UTC, udi-speedb commented
@Yuval-Ariel - Thanks for the review.
I will now rebase on latest main and squash the commits.

2022-11-21 06:05 UTC, merged