Add RefreshOptions method to support live config changes
speedb-io/speedb pull request #294
Opened 2022-12-13 15:50 UTC by mrambacher

Added a method and options to support reading configuration changes to options periodically while a process is running.  Every "refresh_options_sec", the periodic task scheduler runs a task to check if the "refresh_options_file" exists.  If it does, the file is loaded as an options file and the mutable options from the file are updated in the running process (via SetDBOptions and SetOptions).  Once updated, the refresh file is deleted.  If an error occurs, it will be written to the log file.

Note that the file is read as an Options file and must be a valid Options file.  This means that the file must have a DBOptions section and at least one ColumnFamilyOptions section.  Only options that are mutable can be in this file -- immutable options will cause an error and abort the processing.

Additionally, note that TableFactory options must be specified as part of the ColumnFamilyOptions.  For example, to change the block size, the "table_factory.block_size" option should be set in the appropriate ColumnFamilyOptions.  Options set in a TableFactory section will be ignored.

Currently tested manually via db_bench.  Unit tests will be forthcoming.

2022-12-14 11:33 UTC, udi-speedb commented
@mrambacher - Is there an issue for this PR?
If not, please create one.
Either way, please link the issue with this PR. Thanks

2022-12-19 08:04 UTC, udi-speedb commented
Why is this feature not available in RocksDB Lite? 
Actually, for my edification, what should be the capabilities / restrictions on RocksDB lite in general? 
Are you aware of any resource specifying this?

2022-12-19 09:02 UTC, udi-speedb commented
I think we should add support for this feature in db_stress and crash testing

2022-12-19 09:23 UTC, udi-speedb requested changes

2022-12-19 09:23 UTC, udi-speedb commented on db/db_impl/db_impl.cc
> +          if (!s.ok()) {
Does failure to update a cf's options mean we end up with a partial update?
We may have updated some of the cf-s and we'll skip the rest.

2022-12-19 09:23 UTC, udi-speedb commented on db/db_impl/db_impl.cc
> +  s = fs_->DeleteFile(new_options_file, IOOptions(), nullptr);
In case we have failed deleting this file (which may or may not be a valid options file that we have just successfully updated or failed to update), does this mean we will repeat the process as long as the file is there?

2022-12-19 09:23 UTC, udi-speedb commented on db/db_impl/db_impl.cc
> +        auto cfd = versions_->GetColumnFamilySet()->GetColumnFamily(cf_name);
Is it possible to hold a pointer a dropped CF at this point?
If it is possible, is there any need or benefit in avoiding the update to a dropped CF?

2022-12-19 13:22 UTC, mrambacher commented
> Why is this feature not available in RocksDB Lite? Actually, for my edification, what should be the capabilities / restrictions on RocksDB lite in general? Are you aware of any resource specifying this?

The PeriodicTaskScheduler is not available in LITE mode.  I do not know why.  I do not know how things were decided LITE or not.

2022-12-19 13:27 UTC, mrambacher commented on db/db_impl/db_impl.cc
> +  }
This is exactly the same code as under the other PeriodicTasks (like RefreshStats).  I am not positive of the rules for the mutex_, but followed the other examples.

2022-12-19 14:05 UTC, udi-speedb commented on options/db_options.cc
> +      refresh_options_file(options.refresh_options_file),
Oh, I haven't noticed that it's not a standard copy ctor.

2022-12-19 16:22 UTC, mrambacher commented on db/db_impl/db_impl.cc
> +  if (mutable_db_options_.refresh_options_sec > 0) {
If the file is not set, the code defaults to "Options.new"

2022-12-19 16:25 UTC, mrambacher commented on db/db_impl/db_impl.cc
> +          if (!s.ok()) {
If updating the DBOptions fails, the entire process fails.

If any of the ColumnFamilyOptions updates fails, the DBOptions will be updated (if changed) and any other ColumnFamilyOptions will still be updated.  It is extremely difficult to roll back to the previous version of the options, as you cannot tell if any background task (such as compaction) started during the refresh options process.  Because of this, the code prints an error if the options upgrade fails but continues anyway.

2023-01-02 11:40 UTC, udi-speedb requested changes

2023-01-02 11:40 UTC, udi-speedb commented on db/db_options_test.cc
> +  TEST_SYNC_POINT("DBOptionsTest::WaitForUpdates");
I think the following race might happen:
- The DBImpl::RefreshOptions() will run and reach the DBImpl::RefreshOptions::Complete sync point
- PersistRocksDBOptions() called
- DBOptionsTest::WaitForUpdates sync point
In that case the test will pass, but without actually testing what you intend here.

May also apply to other unit tests here.
 I think you should first persist the options file, and only then enable sync point processing. That way you would ensure that the refresh task occurred after the options file you have prepared in on disk.

Another way (and also something you need to test IMO is to verify that the file you have prepared was indeed deleted before checking that the test has performed as expected. That would guarantee that the file was used for a refresh.

2023-01-02 11:40 UTC, udi-speedb commented on db/db_options_test.cc
> +  TEST_SYNC_POINT("DBOptionsTest::WaitForUpdates");
I would prefer to see that a file that contains just an empty DBOptions + CFOptions passes parsing and then test files that contains just one of them.

2023-01-02 11:40 UTC, udi-speedb commented on db/db_options_test.cc
> +  ASSERT_OK(CreateFile(fs, options.refresh_options_file, "fred", false));
It could have failed at this point already by looking for Options.New and just not finding it. You have no verification that the callback was indeed called.

2023-01-02 11:40 UTC, udi-speedb commented on db/db_options_test.cc
> +
A few comments about the unit tests:
- You are using the name Options.New as the file name in the test while the default is Options.new. It might be preferable to pick a name that will be different also in case insensitive file systems (Windows?).
- I suggest adding tests for the following cases:
  - That the file is indeed deleted after a refresh cycle?
  - The specified file in not found during a refresh cycle (refresh_options_file is not empty)
  - refresh_options_file is empty but the file by the default name Options.new is found as expected and updates the options
  - The file specified is a binary file
  - Multiple refreshes, each time with a different contents of the same file
  - Multiple refreshes, the name of the file changes 
  - Having options for a CF that doesn't exist 
  - An invalid file name (invalid characters in the path)
-

2023-01-02 13:37 UTC, udi-speedb requested changes

2023-01-02 13:37 UTC, udi-speedb commented on db_stress_tool/db_stress_test_base.cc
> +#endif  // ROCKSDB_LITE
This will allow the db_stress user to set a refresh rate & file. However, to actually stress test this feature we need to be able to actually create options files to be used by the production code.

2023-01-03 17:52 UTC, mrambacher commented on db/db_options_test.cc
> +  SyncPoint::GetInstance()->DisableProcessing();
We can/could/should.  I would consider this a general issue that should be solved in the base test class destructor myself and handled generally.  

If you wish for me to fix it for this specific test, I can but wonder about scope/feature creep.

2023-01-04 03:55 UTC, udi-speedb commented on db/db_options_test.cc
> +  SyncPoint::GetInstance()->DisableProcessing();
I agree. However, adding new tests that duplicate the cleanup code is bad practice IMO. I would just add a TearDown() to DBOptionsTest to do the cleanup and remove it from your **new** unit tests.

2023-01-06 02:14 UTC, mrambacher commented on db_stress_tool/db_stress_test_base.cc
> +#endif  // ROCKSDB_LITE
I agree that we need such a tool.  I hope to work on one in the near future under a separate PR (for general use as well as this stress test).

2023-01-06 16:43 UTC, mrambacher commented on db/db_options_test.cc
> +  SyncPoint::GetInstance()->DisableProcessing();
Added code to the destructor.

2023-01-06 16:44 UTC, mrambacher commented on db/db_options_test.cc
> +  TEST_SYNC_POINT("DBOptionsTest::WaitForUpdates");
Added a method in the test to deal with the sync points and validate that the file is deleted upon return.  When the file is valid, the test also will validate that the settings have been applied.

2023-01-06 16:46 UTC, mrambacher commented on db/db_options_test.cc
> +  ASSERT_OK(CreateFile(fs, options.refresh_options_file, "fred", false));
Added a method to validate that the options file that was written is deleted after the sync point.

2023-01-17 19:36 UTC, udi-speedb approved these changes

2023-02-07 08:18 UTC, Yuval-Ariel commented
@mrambacher  , it seems the checks have failed.. how is this in QA?

2023-02-07 12:59 UTC, udi-speedb commented
@Yuval-Ariel I have already reviewed this. Has anything changed that needs another review?

2023-02-07 13:22 UTC, Yuval-Ariel commented
@udi-speedb all the approved reviews were removed for some reason.. and the merging needs at least one approval.

2023-02-07 13:57 UTC, udi-speedb commented
Oh, I see. OK. Evil @maxb-io modified (per my request) the policy so that whenever a push is made to an already approved PR, the approval is revoked and the PR needs to be approved again. This is to verify that if anyone updates an already approved PR (usually just squashing / rebasing), it will not go unnoticed and retain its approved state in case an (not less evil) person pushed real content.

2023-02-07 13:58 UTC, udi-speedb approved these changes

2023-02-11 07:19 UTC, udi-speedb approved these changes

2023-02-11 12:32 UTC, merged