Update HISTORY.md
speedb-io/speedb pull request #316
Opened 2022-12-26 10:03 UTC by bosmatt

Updated history with coconut release content.

2022-12-26 13:06 UTC, Yuval-Ariel commented
why do only the first part have working links to the PRs and the rest dont?

2022-12-26 13:07 UTC, Yuval-Ariel commented
can you elaborate a bit more about the new features so readers will have a general idea what its doing without going into the links

2023-01-01 07:49 UTC, Yuval-Ariel commented
also, we should stick with the rocksdb way of only including issues that affect the user

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* cmake: clean up on successful runs and randomise test scheduling (#202)
this is an enhancement. not a bug

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* build: add a version build-tag for non-release builds (#156)
this is an enhancement. not a bug

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* build: support ccache and sccache in the Makefile build (#170)
this is an enhancement. not a bug

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* Update README.md
can be removed or provide more info

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* docs: fix instructions for building Speedb in README.md and INSTALL.md
missing issue number

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* readme typo fix by @azmisaquib (#223)
change to "docs: README.md typo fix"

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* build: correctly handle merge commits when calculating a build tag (#207)
this is issue 225 and not 207

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* Update HISTORY.md (#239)
remove or provide more info. is this a bug?

2023-01-19 09:07 UTC, Yuval-Ariel commented on HISTORY.md
> +* db_bench: add benchmark - seektodeletedranges  (#201)
also not a bug

2023-01-19 10:52 UTC, Yuval-Ariel commented on HISTORY.md
> +* db_bench: Support '--groups' in addition to '-groups' (#283) by @udi-speedb in https://github.com/speedb-io/speedb/pull/295
this: " * db_bench: Support '--groups' in addition to '-groups' (#283) by @udi-speedb in https://github.com/speedb-io/speedb/pull/295 " 
is a valuable improvement?

2023-01-19 13:29 UTC, bosmatt commented on HISTORY.md
> +* db_bench: Support '--groups' in addition to '-groups' (#283) by @udi-speedb in https://github.com/speedb-io/speedb/pull/295
As I see it, the history file should include all the changes, even if they are very minor.

2023-01-19 15:18 UTC, Yuval-Ariel commented on HISTORY.md
> +* db_bench: Support '--groups' in addition to '-groups' (#283) by @udi-speedb in https://github.com/speedb-io/speedb/pull/295
sure

2023-01-19 15:55 UTC, mrambacher commented on HISTORY.md
> +* Dynamic delayed write mechanism for performance stabilization by @Yuval-Ariel in https://github.com/speedb-io/speedb/pull/281 https://docs.speedb.dev/documentation/speedb-features/dynamic-delayed-w
Typically the author is not referred to in the HISTORY file.  That info can already be obtained from the PR if necessary.

Also, I would use links so it shows the PR number rather than the full URL

2023-01-30 07:44 UTC, bosmatt commented on HISTORY.md
> +* Dynamic delayed write mechanism for performance stabilization by @Yuval-Ariel in https://github.com/speedb-io/speedb/pull/281 https://docs.speedb.dev/documentation/speedb-features/dynamic-delayed-w
Fixed

2023-02-08 11:01 UTC, Yuval-Ariel requested changes
there are still many things that need to be fixed

2023-05-16 14:29 UTC, closed without merging