db_bench: fix for issue #290
speedb-io/speedb pull request #370
Opened 2023-01-19 05:05 UTC by andy-byers

Changed db_bench so that when using multiple databases (num_multi_db > 1) we only destroy databases that were used for the current group (databases specified in dbs_to_use).

2023-01-23 05:15 UTC, udi-speedb commented
Hi @andy-byers,
Thanks a lot for working on this issue and submitting the PR.
Your PR failed our checks due to a minor technical issue. Did you get an email from GitHub with a notification about it?
Anyway, the way to fix that is to run the command:
`make format`
This command runs automatic code formatting checks that make sure the code conforms to certain coding conventions, and proposes to "fix" your code. You can just allow the tool to automatically fix your code and amend the last commit and re-submit the PR.

2023-01-23 15:18 UTC, andy-byers commented
Hey @udi-speedb, thanks for the feedback. I'll run `make format` and push again.

2023-01-23 17:39 UTC, andy-byers commented
I figured I would explain some of my reasoning behind these changes. First, in `OpenAllDbs()`, we will only open databases in `dbs_` that were not already opened (both their `db` and `opt_txn_db` members are `nullptr`). Then, in `DestroyUsedDbs()` (renamed from `DestroyAllDbs()`), we destroy the databases whose indices are in `db_idxs_to_use`. Instead of calling the free function `DeleteDbs()` which clears `dbs_`, we call the `DeleteDbs()` member of the specific `DBWithColumnFamilies` instances we want to delete, which makes sure both the `db` and `opt_txn_db` members are set to `nullptr`. Note that `FLAGS_num_multi_db` won't ever change between groups, so we won't leak opened but unused databases in `OpenAllDbs()`. Also, the free `DeleteDBs()` is run in the benchmark class destructor, so all databases should be cleaned up at the end. Let me know if there are any questions or concerns.

On a side note, it doesn't look like there are any tests in `db_bench_tool_test.cc` that exercise the `-num_multi_db` or `-dbs_to_use` options. I'd be happy to write some if that is deemed necessary. Thanks!

2023-01-24 06:11 UTC, udi-speedb requested changes

2023-01-24 06:21 UTC, udi-speedb commented
@andy-byers Thanks for fixing the formatting issue and for the detailed explanation of your changes.
Other than the minor comment I have give, it looks good to me.
Unrelated to your changes, but something I have come across during the review, and would like to hear your opinion about, is the code in `DBWithColumnFamilies::DeleteDBs()`:
```
#ifndef ROCKSDB_LITE    
   if (opt_txn_db) {    
      delete opt_txn_db;    
      opt_txn_db = nullptr;    
    } else {    
      delete db;    
      db = nullptr;    
    }    
#else    
```
Shouldn't the `db` member be unconditionally set to nullptr (even when `opt_txn_db != nullptr`)?

2023-01-24 06:23 UTC, udi-speedb commented
@andy-byers As for your proposal to add tests in `db_bench_tool_test.cc`, that would be great.
If you are willing to do so, would you like to add them as part of this PR or do you prefer that we open a separate issue for those?

2023-01-24 18:27 UTC, andy-byers commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
I totally missed that, thank you. As for your comment below, you're right, the `db` member needs to be nulled out unconditionally. Then the check for `opt_txn_db` can be removed.

2023-01-24 18:34 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
> I totally missed that, thank you. As for your comment below, you're right, the `db` member needs to be nulled out unconditionally. Then the check for `opt_txn_db` can be removed.

However, please do not change that as part of this PR. This is a RocksDB issue (=> upstreamable from our standpoint) and, therefore, should be handled in a separate issue (dbs_to_use_ is a Speedb only addition).
I will open a separate issue for that.

2023-01-24 20:03 UTC, andy-byers commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
Sounds good. I just pushed a fix for this change. Does that look okay? It should be sufficient until the other issue is fixed, at which point the code can be simplified as discussed.

2023-01-25 13:57 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
> Sounds good. I just pushed a fix for this change. Does that look okay? It should be sufficient until the other issue is fixed, at which point the code can be simplified as discussed.

Thanks. I only now thought about it, but couldn't you just replace the following block of code:
```
#ifndef ROCKSDB_LITE
        if (FLAGS_optimistic_transaction_db) {
          if (dbs_[i].opt_txn_db) {
            continue;
          }
        } else if (dbs_[i].db) {
          continue;
        }
#else   // ROCKSDB_LITE
        if (dbs_[i].db) {
          continue;
        }
#endif  // ROCKSDB_LITE

```
With this:
```
if (dbs_[i].db) {
  continue;
}

2023-01-25 18:23 UTC, andy-byers commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
That's actually what I originally wanted to do. Unfortunately, when the `optimistic_transaction_db` option is used, we can't depend on the `db` member anymore, since it is set to point to the base DB in `Benchmark::OpenDb`, but not nulled out in `DBWithColumnFamilies::DeleteDBs()`. I tried, and it ends up crashing. Once the RocksDB issue gets fixed (moving the `db = nullptr` out of the `else` block in `DBWithColumnFamilies::DeleteDBs()`), we should be able to make that change.

2023-01-26 05:30 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
Thanks. I see.

I have opened #374 to fix the RocksDB issue (nullifying `db_`)

Please let me know if you would you like to add tests as part of this PR. If not, I will approve it as is. I can open another issue to add the tests.

2023-01-26 18:49 UTC, andy-byers commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
I was wondering, do you know how the benchmark tests are built and run? `db_bench_tool_test` is provided as a target in the root Makefile, but isn't mentioned anywhere else that I could find. I built it and ran it (from main) with no arguments, and it actually trips some assertions. Is it supposed to be run with some arguments?

I think adding those tests might be a bit more complicated than I originally thought, and would probably be better off in a different issue.

2023-01-27 06:56 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
I am not familiar with db_bench_test_tool so I can't help you there. I will look at it in the near future to get to know it.
Thanks so much for working on this issue.
Please squash your commits and also put the issue number in parenthesis in the commit message (#290). I will then approve it.

2023-01-27 23:17 UTC, andy-byers commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
I had to force push, but I got everything squashed and fixed the commit message.

Thank you for your help! I'll continue to look into the benchmark tests and file an issue if necessary.

2023-01-29 04:44 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +        if (dbs_[i].db || dbs_[i].opt_txn_db) {
Thanks so much again for working on this.
Approving the PR.

2023-01-29 04:45 UTC, udi-speedb approved these changes

2023-02-11 12:38 UTC, merged