add speedb is awesome example to support new getting started instruct…
speedb-io/speedb pull request #382
Opened 2023-01-31 14:31 UTC by RoyBenMoshe

…ions(#378)

2023-01-31 15:05 UTC, udi-speedb requested changes

2023-01-31 15:05 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  DB::Open(options, kDBPath, &db);
DB::Open() returns a status and may fail. It is definitely recommended to check the status and act accordingly.

2023-01-31 15:05 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  db->Put(WriteOptions(), key, val);
Same here. Please check the return status

2023-01-31 15:05 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  db->Get(ReadOptions(), "key", &value);
Same here. Please check the return status

2023-01-31 15:05 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  db->Close();
Same here. Please check the return status

2023-01-31 15:05 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  std::string value;
It may be preferable to have names such as put_value / read_value to the 2 variables (rather than val / value) to emphasize their role.

2023-01-31 18:17 UTC, RoyBenMoshe commented on examples/Makefile
> -	rm -rf ./simple_example ./column_families_example ./compact_files_example ./compaction_filter_example ./c_simple_example c_simple_example.o ./optimistic_transaction_example ./transaction_example ./o
this is an additional example

2023-01-31 18:28 UTC, RoyBenMoshe commented on examples/speedb_is_awesome_example.cc
> +  std::string key = "key";
string was changed

2023-01-31 18:28 UTC, RoyBenMoshe commented on examples/speedb_is_awesome_example.cc
> +  DB::Open(options, kDBPath, &db);
Status is now checked (for all places)

2023-02-01 04:42 UTC, udi-speedb requested changes

2023-02-01 04:42 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  assert(get_value == put_val);
Really being petty here, but put_val / get_value (inconsistent)

2023-02-01 04:42 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  DB* db;
It's good practice to always explicitly init variables so I would init to `nullptr`.

2023-02-01 04:42 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  s = db->Get(ReadOptions(), "key_1", &get_value);
Why aren't you using `put_key` instead of the literal `"key_1"`?

2023-02-01 04:42 UTC, udi-speedb commented on examples/speedb_is_awesome_example.cc
> +  std::string put_key = "key_1";
Better call `put_key` just key as it it used (should be used) for both put & get.

2023-02-01 11:51 UTC, RoyBenMoshe commented on examples/speedb_is_awesome_example.cc
> +  DB* db;
done for all

2023-02-01 12:01 UTC, udi-speedb approved these changes

2023-02-01 12:03 UTC, udi-speedb commented
@RoyBenMoshe - Please sqaush the commits into a single commit and insert a space before the (#378):
`instructions(#378)`
Thanks

2023-02-05 08:46 UTC, merged