windows build failed in speedb_paired_bloom_internal files due to bad…
speedb-io/speedb pull request #384
Opened 2023-02-02 13:24 UTC by ayulas

… used of double / uint32 casting #383

2023-02-02 14:17 UTC, udi-speedb submitted a review, later dismissed

2023-02-06 11:43 UTC, udi-speedb commented
@ayulas - A preliminary question: Is this PR ready for review with all of the planned changes?
Does it build successfully as it is on Windows?
Do we run make check (or equivalent) on Windows and all of the unit tests pass?
Same question for additional QA tests on Windows?

2023-02-06 11:47 UTC, udi-speedb commented
Are all of the changes needed to successfully build on Windows or does this PR contain functional changes that are not related to being able to successfully compile / build on Windows?

2023-02-06 11:51 UTC, udi-speedb requested changes

2023-02-06 11:51 UTC, udi-speedb commented on port/win/port_win.h
> +#define RWMutexWr RWMutex
Why don't you use:
`using RWMutexWr = RWMutex;`

And please also add a comment to explain why that is needed / what is RWMutexWr.
And, is RWMutexWr not needed in Windows as it was needed in Posix-based environments?

2023-02-06 11:51 UTC, udi-speedb commented on plugin/speedb/memtable/hash_spd_rep.cc
> +                                size_t total_merge_vector_elements) {
Is adding a parameter to the method part of passing the build on Windows or is it related to some other issue?

2023-02-06 18:58 UTC, ayulas commented
i wouldnt push and send to qa and run CI if it wasnt built successfully and got approve from max
i took this ticket to help max compilation issue. its not related to qa test and it was supposed handle this.
all the changes here are related to compile errors and warnings

2023-02-06 18:59 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +                                size_t total_merge_vector_elements) {
compile issue

2023-02-06 18:59 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +                                size_t total_merge_vector_elements) {
@hilikspdb pls review the memtable windows compile changes

2023-02-07 08:02 UTC, Yuval-Ariel approved these changes

2023-02-07 08:40 UTC, Yuval-Ariel approved these changes

2023-02-07 12:50 UTC, merged