Add Filter::CreateFromString to Java
speedb-io/speedb pull request #387
Opened 2023-02-07 00:22 UTC by mrambacher

This PR adds the ability to create a Filter (FilterPolicy) in Java via the CreateFromString methodology.  This change allows the other filter policies (such as Ribbon Filter and plugin filters) to be created in Java using the C++ infrastructure.

2023-02-07 06:41 UTC, udi-speedb commented
@mrambacher - Preliminary question: Do you have any means to check the change / run the FilterTest.java to verify it passes?

2023-02-07 12:37 UTC, mrambacher commented
> @mrambacher - Preliminary question: Do you have any means to check the change / run the FilterTest.java to verify it passes?

I ran "make jtest", which runs the FilterTest

2023-02-07 12:39 UTC, udi-speedb commented
> > @mrambacher - Preliminary question: Do you have any means to check the change / run the FilterTest.java to verify it passes?
> 
> I ran "make jtest", which runs the FilterTest

OK. Do you think that's enough to feel comfortable releasing this or should we test it in some real java environment? I am asking since my knowledge of Java is very limited

2023-02-28 04:12 UTC, udi-speedb commented
> > > @mrambacher - Preliminary question: Do you have any means to check the change / run the FilterTest.java to verify it passes?
> > 
> > 
> > I ran "make jtest", which runs the FilterTest
> 
> OK. Do you think that's enough to feel comfortable releasing this or should we test it in some real java environment? I am asking since my knowledge of Java is very limited

@mrambacher - You haven't answered my question. Please do

2023-02-28 14:11 UTC, udi-speedb requested changes

2023-02-28 14:11 UTC, udi-speedb commented on java/src/test/java/org/rocksdb/FilterTest.java
> +  }
Please add a test to create our filter as well. This is both expected IMO (as this is our new type) and will also test our ability to create a plugin using the JNI.

2023-02-28 14:11 UTC, udi-speedb commented on java/src/test/java/org/rocksdb/FilterTest.java
> +  }
What are you testing here?
Are you expecting an exception to be thrown? How is this tested?

2023-03-07 16:46 UTC, mrambacher commented on java/rocksjni/portal.h
> +  }
> The function returns, in case of errors, sometimes negative error codes instead of valid pointers. Is it OK because an exception is thrown and, therefore, the status is never actually returned (just a way to let the Java code "compile")? It's confusing IMO. Why not return a nullptr converted to jlong or 0 (as in Java_org_rocksdb_BackupEngineOptions_newBackupEngineOptions) to show the reader that it's a null pointer? You can also document the reason for returning the "null pointer" (the reason for the error).

I was following the example used by the DB code where a Status DB::Put() would throw an exception based on the Status code.  If there is a different example that makes more sense, I am willing to follow it instead.

2023-03-12 03:39 UTC, udi-speedb requested changes

2023-03-12 03:39 UTC, udi-speedb commented on java/rocksjni/portal.h
> +  }
I just gave one in my comment above: Java_org_rocksdb_BackupEngine_open
And others: Java_org_rocksdb_BackupEngine_getCorruptedBackups

2023-03-12 03:39 UTC, udi-speedb commented on java/rocksjni/portal.h
> +  }
I still do not understand why do you need to explicitly override the cpp defaults:
```
  // When true, any unused options will be ignored and OK will be returned
  bool ignore_unknown_options = false;

  // When true, any unsupported options will be ignored and OK will be returned
  bool ignore_unsupported_options = true;

  // If the strings are escaped (old-style?)
  bool input_strings_escaped = true;

  // Whether or not to invoke PrepareOptions after configure is called.
  bool invoke_prepare_options = true;
```

2023-03-12 03:39 UTC, udi-speedb commented
@mrambacher - I have replied on the updates. Please note that there are still some comments that you haven't addressed.
Thanks

2023-03-12 21:59 UTC, mrambacher commented on java/rocksjni/portal.h
> +  }
The only value that is different than the default is "ignore_unsupported_options=false".  The rest match the default.  This value would be nice to default to false, but would cause a lot of old code to fail.  I could not make "unsupported=false" for historical reasons; since Java does not have this history, we can turn this off here.

2023-03-12 22:01 UTC, mrambacher commented
> > > > @mrambacher - Preliminary question: Do you have any means to check the change / run the FilterTest.java to verify it passes?
> > > 
> > > 
> > > I ran "make jtest", which runs the FilterTest
> > 
> > 
> > OK. Do you think that's enough to feel comfortable releasing this or should we test it in some real java environment? I am asking since my knowledge of Java is very limited
> 
> @mrambacher - You haven't answered my question. Please do

How else would you like this tested?  I do not see where the the other filter code is tested in any more depth than this API.

2023-03-12 22:02 UTC, mrambacher commented on java/src/test/java/org/rocksdb/FilterTest.java
> +  }
This test will throw an exception which is expected (and caught) by the test harness.

2023-03-21 03:07 UTC, udi-speedb commented
> > > > @mrambacher - Preliminary question: Do you have any means to check the change / run the FilterTest.java to verify it passes?
> > > 
> > > 
> > > I ran "make jtest", which runs the FilterTest
> > 
> > 
> > OK. Do you think that's enough to feel comfortable releasing this or should we test it in some real java environment? I am asking since my knowledge of Java is very limited
> 
> @mrambacher - You haven't answered my question. Please do

@mrambacher - Could you please answer

2023-03-21 03:08 UTC, udi-speedb commented on java/rocksjni/portal.h
> +  }
I do. Thanks

2023-03-21 03:10 UTC, udi-speedb commented on java/rocksjni/portal.h
> +  }
I think it's best to have the JAVA default be the same as the CPP defaults. That way JAVA users get the same behaviour as cpp users by default.

2023-03-21 03:18 UTC, udi-speedb commented
@mrambacher - Still some comments / questions . Thanks

2023-03-21 10:23 UTC, mrambacher commented on java/src/test/java/org/rocksdb/FilterTest.java
> +  }
> @mrambacher - Could you please somehow address this comment?

@udi-speedb There is a test added under plugin/speedb/java for the Speedb-specific test.

2023-03-21 10:27 UTC, mrambacher commented on java/rocksjni/portal.h
> +  }
@udi-speedb I can change it so the defaults match the C++.  However, I am not certain that is what is desired in this case.  The C++ ones are what they are to support older settings.  For example, the default for "ignore_unsupported_options=true" would mean that attempting to create a filter that does not exist may return OK when it should return an error.   This is a historical artifact as C++ behaved this way before the new infrastructure was added and needs to for compatibility.  Java -- having no such compatibility issues, since this is new code -- can return errors properly under those conditions.

If you still feel strongly about it, I can make the defaults match.  However, I do not know I agree that is the right thing to do.

2023-03-21 12:40 UTC, udi-speedb approved these changes

2023-04-17 08:31 UTC, Yuval-Ariel commented
@mrambacher , this can be merged but please squash the commits when you do and provide a descriptive commit msg

2023-04-18 22:03 UTC, mrambacher commented
> @mrambacher , this can be merged but please squash the commits when you do and provide a descriptive commit msg

@Yuval-Ariel I have no idea how to do a squash since my branch also contains updates merged from main.  Is there a reason "squash and merge" is insufficient?

2023-04-19 05:19 UTC, merged