Add useBaseAddress to OptionTypeInfo
speedb-io/speedb pull request #397
Opened 2023-02-10 18:32 UTC by mrambacher

(This replaces #308, which will be abandoned due to git branching issues).

When an OptionsTypeInfo is defined, it is passed the offset of the field in question. This offset is the relative location of the field in the structure being analyzed. This PR adds a "useBaseAddress" flag that tells the option system to use the base address rather than the offset to any custom functions.  The flag is only used if a custom function is used and is ignored if using the default behaviors.

This new flag is useful when there are relationships between fields in the structure. For example:

If a std::shared_ptr shared_env value is added to the DBOptions, the "shared" and "env" can be marked as useBase. This would allow the system to serialize either of the values (either shared or env and not both) and allow the Create method to update the other value.
For things like Compaction, the different Options (CompactionOptionsFIFO/Universal) could be skipped during serialization if they did not apply (so if FIFO was specified, do not store or validate Universal options).
Fields that are specific to certain implementations could be moved/associated with the implementation.
When multiple fields are validated/prepared/sanitized together, the code can be placed in the OptionsTypeInfo rather than writing class-specific implementations of these methods. For example, the BlockBasedTableOptions have fields that are related. Using this new flag allows the relationship to be initialized and validated without the class methods.

2023-02-13 18:06 UTC, RoyBenMoshe commented on table/block_based/block_based_table_factory.cc
> +         OptionTypeInfo(offsetof(struct BlockBasedTableOptions, no_block_cache),
* I see in this file some differences from the old PR, like lines 259-261 that were deleted in the old PR, is it ok?
* Did you test the new functionality? How did you test it?

2023-02-14 22:56 UTC, mrambacher commented on table/block_based/block_based_table_factory.cc
> +         OptionTypeInfo(offsetof(struct BlockBasedTableOptions, no_block_cache),
Should be fixed.

I tested this code by running the unit tests.

2023-02-15 10:38 UTC, RoyBenMoshe commented on table/block_based/block_based_table_factory.cc
> +         OptionTypeInfo(offsetof(struct BlockBasedTableOptions, no_block_cache),
* I think that might be some more differences in addition to the one above, please check it.
* Can you please elaborate how the new functionality(the definition and the use of the relations between fields) is tested with the current unit tests, aren't we want to add specific tests for it?

2023-03-12 03:20 UTC, udi-speedb commented
@mrambacher - Could you please comment / reply / handle the last review comments @RoyBenMoshe gave?

2023-04-27 20:43 UTC, mrambacher commented on table/block_based/block_based_table_factory.cc
> +         OptionTypeInfo(offsetof(struct BlockBasedTableOptions, no_block_cache),
> * I think that might be some more differences in addition to the one above, please check it.

I think that the differences should be resolved now.

> * Can you please elaborate how the new functionality(the definition and the use of the relations between fields) is tested with the current unit tests, aren't we want to add specific tests for it?

I added a unit test to do this relationship explicitly

2023-06-07 06:19 UTC, udi-speedb submitted a review, later dismissed

2023-10-18 10:32 UTC, ofriedma requested changes

2023-10-18 10:32 UTC, ofriedma commented on table/block_based/block_based_table_factory.cc
> +  // the code is needed here as well in order to support LITE mode
RocksDB LITE has been removed

2023-10-18 15:44 UTC, mrambacher commented on table/block_based/block_based_table_factory.cc
> +  //**TODO: Move this code into PrepareOptions
@ofriedma This file has been reverted to match that of main.  I am not sure why it is still showing up as different

2023-10-18 15:45 UTC, mrambacher commented on table/block_based/block_based_table_factory.cc
> +  // the code is needed here as well in order to support LITE mode
> RocksDB LITE has been removed

This file has not changed from main.  Not sure why it is in this review any longer.

2023-10-19 12:11 UTC, ofriedma approved these changes

2023-10-24 13:09 UTC, ofriedma approved these changes

2023-10-29 06:15 UTC, udi-speedb commented
@mrambacher, @ofriedma - Please handle this PR so we may merge it.
A reminder: It's now mandatory to resolve all of the comments (the reviewer should resolve) to be able to merge.
Thanks

2023-10-29 10:46 UTC, ofriedma commented
@Yuval-Ariel ready to be merge

2023-10-29 12:47 UTC, udi-speedb commented
@mrambacher - Please fix the license / History issue. Thanks

2023-10-30 12:20 UTC, ofriedma approved these changes

2023-10-30 19:02 UTC, udi-speedb commented
@or - Please review, resolve applicable comments, and indicate when ready to merge. Thanks

2023-10-31 14:07 UTC, ofriedma approved these changes

2023-11-01 08:49 UTC, merged