Skip expired object while using DBWithTtl
speedb-io/speedb pull request #403
Opened 2023-02-15 19:57 UTC by ofriedma

Currently even if objects have been expired we still return them until
compaction delete those objects.

This commit adds a skip_expired_data to the ReadOptions, if this option
is true, it Get, MultiGet and iterator will not return objects that have been
expired by the configured ttl.
Currently this feature does not include support of for Merge
operation.
For Read Only and iterator pinned data the skip_expired_data will be enforced and expired keys
will not be returned.

Resolves: https://github.com/speedb-io/speedb/issues/394 , https://github.com/speedb-io/speedb/issues/417

2023-02-16 05:33 UTC, udi-speedb commented on examples/speedb_with_ttl_example.cc
> +
It may be cleaner, and therefore preferable, to just add a `using namespace ROCKSDB_NAMESPACE` as this is what we want here anyway

2023-02-16 06:05 UTC, udi-speedb commented
Does the partial / hybrid support (Get / MultiGet strict ttl while iterator / merge non-strict ttl) make sense for users? 
I understand that compaction is a background process and, therefore, the user has no way of knowing when the keys would be compacted (and consequently removed), but in this PR a user may issue a Get() -> No key, Iter() -> Key returns, Get() -> No key, which will not happen in non-strict ttl.

2023-02-16 09:47 UTC, ofriedma commented on examples/speedb_with_ttl_example.cc
> +
Done

2023-02-19 04:38 UTC, udi-speedb commented
Please add the issue's / pr's number at the end of the commit message

2023-02-19 05:44 UTC, udi-speedb requested changes

2023-02-19 05:44 UTC, udi-speedb commented on utilities/ttl/db_ttl_impl.h
> +  SystemClock* GetClock() { return clock_; }
I think this one is not in use as well

2023-02-19 05:44 UTC, udi-speedb commented on include/rocksdb/options.h
> +  int32_t ttl_skip_expired_data = 0;
Please emphasize that the default (0) means "never-stale"

2023-02-19 05:44 UTC, udi-speedb commented on utilities/ttl/ttl_test.cc
> +}
I would add the following to the test:
1. Show that the value is returned when skip_expired_data == false
2. Show that the value is returned before becoming stale for skip = {false, true} (it might make sense to make this test parametrized)
3. Test behavior for the default ttl value of 0
4. Actually sleeping for 2 seconds make the tests long. I suggest using the sleep mocking utilities they have.
5. Showing that a read options with a larger ttl will avoid skipping

2023-02-19 05:44 UTC, udi-speedb commented on build_tools/check-sources.sh
> +    ':!examples/speedb_with_ttl_example.cc'
Why is this needed here?
Are we missing this for other files we have added?

2023-02-19 05:44 UTC, udi-speedb commented on examples/CMakeLists.txt
> +  target_link_libraries(speedb_is_awesome_examle)
the target_link_libraries is indented differently (in both speedb_with_ttl_example and speedb_is_awesome_examle) - I am not using cmake. Does this have a real impact on the outcome?
BTW - speedb_is_awesome_examle has a typo - **example**, not **examle**
I must have missed these in my review of @RoyBenMoshe speedb_is_awesome_example PR. 

Did we verify that it runs correctly under cmake?

2023-02-19 05:44 UTC, udi-speedb commented on examples/Makefile
> +all: simple_example column_families_example compaction_filter_example compact_files_example c_simple_example optimistic_transaction_example transaction_example options_file_example rocksdb_backup_res
Could we shorten the line and use multi-lines?

2023-02-19 05:44 UTC, udi-speedb commented on examples/Makefile
> +	rm -rf ./simple_example ./column_families_example ./compact_files_example ./compaction_filter_example ./c_simple_example c_simple_example.o ./optimistic_transaction_example ./transaction_example ./o
Same here. Too long

2023-02-19 05:44 UTC, udi-speedb commented on utilities/ttl/db_ttl_impl.cc
> +  options->ttl_skip_expired_data = ttl;
This doesn't make sense. You have added it as an option for the user, but overwrite it using the ttl value specified. That means that it's not truly a user-settable option

2023-02-19 05:44 UTC, udi-speedb commented on utilities/ttl/ttl_test.cc
> +}
And please add a space line between the tests

2023-02-19 05:44 UTC, udi-speedb commented on utilities/ttl/ttl_test.cc
> +
Same comments as above, but also:

1. Please also test the mutli-get versions that accept a single cf and multiple cf-s
I suggest adding another cf, but have the 2 cf-s have different ttl-s and verifying that each cf complies with its ttl

2023-02-19 09:41 UTC, ofriedma commented on build_tools/check-sources.sh
> +    ':!examples/speedb_with_ttl_example.cc'
it is needed because "using namespace" is not valid in our tests, unless the is being added to this script

2023-03-01 04:36 UTC, udi-speedb commented
Please add the PR's number (#403) at the end of the commit message.

2023-03-01 06:47 UTC, udi-speedb requested changes

2023-03-01 06:47 UTC, udi-speedb commented on utilities/ttl/db_ttl_impl.h
> +  }
A comment applicable to this as well as the other methods below.
As a general rule, header files should include the methods' declarations and not their definitions (implementation). Exceptions exists (e.g., templates and short performance-critical inline methods).

2023-03-01 06:47 UTC, udi-speedb commented on utilities/ttl/db_ttl_impl.h
> +    while (Valid()) {
This is recursive and may potentially iterate recursively over the entire contents of the database if I am not mistaken (=> risk of stack overflow or memory exhaustion, depending on the stack size policy in use).
And, another issue worth considering (in the recursive approach) are the repeated calls to GetCurrentTime() which I think is a rather expensive system call). An iterative solution would allow us to get the time once, and use it for the entire iteration while skipping stale keys.

2023-03-01 06:47 UTC, udi-speedb commented on utilities/ttl/db_ttl_impl.h
> +  }
SeekToLast (applicable to SeekToFirst) should succeed when there is any content in the iterated entity.
Would it be possible for the caller to call one of these on an entity it knows is not empty and expect the iterator to be valid after the call?
By a caller I am also referring to internal RocksDB code that may use this iterator (assuming there is such code).
I am not saying I am aware of such a scenario, just raising the issue so we consciously answer it.

2023-03-01 06:48 UTC, udi-speedb commented
@ofriedma - I have submitted all of your comments except for the ttl_test.cc file
I will add them in the next review cycle, after you update the existing files following my comment.

2023-03-01 13:19 UTC, ofriedma commented on utilities/ttl/db_ttl_impl.h
> +    while (Valid()) {
There is no recursion here, i'm calling Iterator functions and not Ttliterator functions

2023-03-01 13:32 UTC, ofriedma commented on utilities/ttl/db_ttl_impl.h
> +  }
The TtlIterator will have the same behaviour as before these changes if the user didn't send skip_expired flag.
The user should always call Valid() before accessing an iterator after any lookup operation such as Seek() or Next().

2023-03-01 14:43 UTC, udi-speedb commented on utilities/ttl/db_ttl_impl.h
> +  }
I was referring to the case where the user sets skip_expired to true.
But, if indeed the user must always call Valid() then it's a non-issue.
By "user" do you also mean internal RocksDB code that uses the iterator (if there is any such code)?

2023-03-01 15:02 UTC, ofriedma commented on utilities/ttl/db_ttl_impl.h
> +  }
I don't know, but if there is it should be use the lower level impl anyway and the feature is being active only by read options set to true

2023-03-05 09:24 UTC, udi-speedb approved these changes

2023-03-05 09:24 UTC, udi-speedb commented
@ofriedma - Please add the issue's number to the commit message. Thanks

2023-03-06 03:28 UTC, udi-speedb commented
What about ttl support in db_stress?
Does it exist? If not, is it possible to add it?

2023-03-06 03:28 UTC, udi-speedb requested changes

2023-03-06 03:28 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +             "deleted values don't fail");
- If ttl <= 0 the ttl is useless. So, better document this and also validate (below, where applicable)
- How will the user know how to "Carefully specify a large value"? What is a large value?
- You should sanitize (validate) these 2 flags. For example, it doesn't make sense to skip expired data if ttl <= 0.

2023-03-06 03:28 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +      db->num_hot = 1;
- Why are you not supporting ttl / db with ttl when there are multiple column families?
- Why no ttl db when in read only?
- If it is indeed the case, you should add it to the sanitization part. IMO invalid combinations should cause db_bench to abort and not run as the user has explicitly requested for specific behaviour and db_bench is not testing the desired behaviour.
- And, if this code stays, you should refactor somehow the duplicate code in this case and the one below (the else block)

2023-03-06 03:28 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +      }
If Open fails (!s.ok()) we exit below, but, for better readability IMO, I would execute the 3 lines below only if s.ok().

2023-03-06 08:55 UTC, ofriedma commented on tools/db_bench_tool.cc
> +             "deleted values don't fail");
Actually I wanted to keep the same documentation as the db_stress (this is a copy of line by line).
I will try to change it to be better understandable here and add I will sanitise those.

2023-03-22 03:28 UTC, udi-speedb commented
@ofriedma - When you have made up your mind about the ttl support / changes in db_stress please update (following our discussion yesterday). Thanks

2023-03-22 10:43 UTC, ofriedma commented
@udi-speedb about your assumption, it was correct, small ttl is causing failure of the test, which means the test has not been suitable to handle expiration and deletion by db_stress, probably never, I'm getting not found error whether with or without skip_expired_data when use small ttl (--ttl=2)

2023-03-22 11:19 UTC, udi-speedb commented
> @udi-speedb about your assumption, it was correct, small ttl is causing failure of the test, which means the test has not been suitable to handle expiration and deletion by db_stress, probably never, I'm getting not found error whether with or without skip_expired_data when use small ttl (--ttl=2).
> 
> @udi-speedb what do you think we should do in that case?

Thanks for checking this.
I see 2 options:
1. Leave db_stress as is. It wasn't designed to actually test the ttl feature and, I agree that it was probably never tested by FB with ttl. That means we are not really testing our updated TTL feature except via unit tests.
2. Invest in adding ttl debug support. Probably requires being able to know which keys have expired (either via compaction or simply by being too old and not returned via the Get / iterator's retrieval) expired keys. Also requires careful sync between the db_stress code that compares the queried values to the expired values (potential races with compaction).

2023-03-29 16:30 UTC, ofriedma commented
The pull request is ready to be reviewed, will squash it once the review will over.

Thank you

2023-04-02 05:22 UTC, udi-speedb commented
If db_stress will fail if a user is really trying to run it with a reasonable ttl, why not just not touch it at all?

2023-04-02 08:25 UTC, udi-speedb requested changes

2023-04-02 08:25 UTC, udi-speedb commented on utilities/ttl/ttl_test.cc
> +  auto ropts = ReadOptions();
Is skip_expired_data left false on purpose?
Do you expect the test's results to depend on this?
Regardless, worth documenting

2023-04-02 09:46 UTC, ofriedma commented on db_stress_tool/db_stress_test_base.cc
> +  if (gflags::GetCommandLineFlagInfoOrDie("ttl").is_default &&
will add a check for the ttl with skip_expired_data to be greater than 0

2023-04-02 16:14 UTC, ofriedma commented on utilities/ttl/ttl_test.cc
> +  auto ropts = ReadOptions();
@udi-speedb 
I've added documentation and comments, change the name of the strict ttl added a condition to ttl <= 0.
The last thing I need to test is the windows environment will run make check on top of Windows tomorrow.

2023-04-02 18:06 UTC, udi-speedb commented on utilities/ttl/ttl_test.cc
> +  auto ropts = ReadOptions();
OK. Please check with @maxb-io the status of building on Windows. He is very familiar with this subject.

2023-04-02 18:09 UTC, udi-speedb approved these changes

2023-04-03 14:14 UTC, ofriedma commented on utilities/ttl/ttl_test.cc
> +  auto ropts = ReadOptions();
I ran ttl_test on windows, ran without issues

2023-04-03 14:45 UTC, ofriedma commented
@udi-speedb please approve

2023-04-03 15:23 UTC, udi-speedb approved these changes

2023-04-04 05:33 UTC, merged