Dirty memory: connect wbm to global delay
speedb-io/speedb pull request #423
Opened 2023-03-12 12:32 UTC by Yuval-Ariel

closes #114

2023-03-19 12:47 UTC, Yuval-Ariel commented
@udi-speedb , ready for review. 
plz note that the first commit (92b1d8a6a800a5a027e8f2f102a60dbf9eabadf8 ) is currently in another PR (https://github.com/speedb-io/speedb/pull/438) and will be merged before this PR so no need to review its contents.

2023-03-27 06:32 UTC, udi-speedb requested changes

2023-03-27 06:37 UTC, udi-speedb commented
@Yuval-Ariel I have submitted an initial set of comments. I really think the interface of the write controller is needlessly complex and inelegant because it is defined in terms of a db id + cf id.
I suggest using uint64_t identifiers that the write controller will allocate. That way there is no need to worry about id-s wrapping around. You can just have a single uint64_t counter that will be incremented by 1 every allocation.
column families will register / de-register themselves from the write controller as well as the WBM, and the write controller will be unaware of the identity of its registered clients. It will also have a single unordered map to map client is (uint64_t) to its delay.

2023-03-27 08:37 UTC, Yuval-Ariel commented on db/write_controller.cc
> +        min_rate = cf_id_and_rate.second;
i would need to flatten the map first. i'll do it if we decide to proceed with WC assigning ids

2023-03-27 08:49 UTC, Yuval-Ariel commented on db/write_controller.cc
> +    if (db_id_to_write_rate_map_.count(db_id)) {
count returns 1 if exists and 0 if not which is what i want to check. find returns an iterator.. i agree its easier to read but the API seemed more compatible.
as for the assert, i wanted to make the code more durable to unexpected behavior and maluse so i added the check to only erase the db_id if its actually there. but you're right, in the expected case, its a bug. i'll remove the check and add an assert

2023-03-29 08:07 UTC, Yuval-Ariel commented on db/write_controller.cc
> +        min_rate = cf_id_and_rate.second;
done

2023-03-29 08:08 UTC, Yuval-Ariel commented on db/write_controller.cc
> +    if (db_id_to_write_rate_map_.count(db_id)) {
i've seen count() used throughout the code base for this use case so i'll stick with that

2023-03-29 08:09 UTC, Yuval-Ariel commented on db/write_controller.cc
> +  db_id_to_write_rate_map_[db_id] = {};
no longer relevant

2023-03-29 08:10 UTC, Yuval-Ariel commented on db/write_controller.cc
> +  return cf_map.count(cf_id);
same as above

2023-03-29 08:10 UTC, Yuval-Ariel commented on db/write_controller.cc
> +void WriteController::HandleNewDelayReq(uint32_t cf_id, uint64_t db_id,
no longer relevant

2023-03-29 08:10 UTC, Yuval-Ariel commented
i've addressed your concerns. plz rereview

2023-04-02 15:00 UTC, udi-speedb requested changes

2023-04-02 15:02 UTC, udi-speedb commented
@Yuval-Ariel 
I have submitted a first batch of comments as part of this PR.
In addition, I have pushed additional comments on files that are not part of this PR, but are related / part of the entire global delay / write controller feature(s). 
These comments are added as a commit on the branch dirty-mem-connect-wbm-to-global-delay.old-code-comments
Please look at them as well and address them (you may do so as a new commit on that branch and / or we may discuss.

2023-04-02 16:56 UTC, Yuval-Ariel commented on db/write_controller.h
>    void NotifyCV();
this is called from ~StopWriteToken() . why should it be private?

2023-04-02 17:03 UTC, Yuval-Ariel commented on db/write_controller.cc
> +  if (total_delayed_ == 0) {
GetDelayToken() also sets delayed write rate and returns a DelayWriteToken. i want this functionality in separate

2023-04-02 17:05 UTC, Yuval-Ariel commented on db/write_controller.h
what is needlessly included again in write_controller.cc?

2023-04-02 17:05 UTC, Yuval-Ariel commented on db/write_controller.h
> +  void HandleRemoveDelayReq(void* client_id);
how would you write the documentation of this method?

2023-04-02 17:07 UTC, Yuval-Ariel commented on db/write_controller.h
> +  void HandleNewDelayReq(void* client_id, uint64_t cf_write_rate);
sure

2023-04-02 17:15 UTC, Yuval-Ariel commented on db/column_family.cc
> +  }
the problem is that the write_buffer_manager_ is unaware of the value of is_dynamic_delay..

2023-04-02 17:16 UTC, Yuval-Ariel commented on db/column_family.cc
> +  }
and we need to think whether changing this option dynamically makes sense. that hasnt been decided yet..

2023-04-02 17:17 UTC, Yuval-Ariel commented on db/column_family.cc
> +        write_controller_token_.reset();
the token is set when theres a stop requirement. so if theres a stop condition and then a delay condition, we have to remove the stop token..

2023-04-02 18:15 UTC, udi-speedb commented on db/column_family.cc
> +  }
As for the WBM, as with cf-s, is there a problem with the approach that it will always interact with the write controller and the write controller will silently ignore if dynamic delay is false?

2023-04-02 18:18 UTC, udi-speedb commented on db/column_family.cc
> +        write_controller_token_.reset();
OK

2023-04-02 18:20 UTC, udi-speedb commented on db/write_controller.h
>    void NotifyCV();
Missed that

2023-04-02 18:26 UTC, udi-speedb commented on db/write_controller.h
<mutex>

2023-04-02 18:29 UTC, udi-speedb commented on db/write_controller.h
> +  void HandleRemoveDelayReq(void* client_id);
How about:
Removes a client's delay and update the wc's effective delayed write rate if applicable

2023-04-03 03:06 UTC, udi-speedb commented
Just thought of a potential issue to use pointers for client id-s of the WC. Since memory allocators may reuse released memory, you may have a race in which the memory of a deregistering client is released and immediately allocated to a new entity that registers with the WC. For example, a deleted CF and a newly created CF (could be deleted in one DB and created in another).

2023-04-03 03:37 UTC, udi-speedb requested changes

2023-04-03 03:37 UTC, udi-speedb commented on include/rocksdb/write_buffer_manager.h
> +  static constexpr uint64_t kWBMId = 0U;
I think it's not in use and may be deleted

2023-04-03 03:37 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +      done = coded_usage_state_.compare_exchange_weak(old_coded_usage_state,
has_update_succeeded? Maybe should be renamed to done?

2023-04-03 03:37 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +        UpdateControllerDelayState();
I would pass new_coded_usage_state to verify that we are consistent with the coded value with which we arrived to this point

2023-04-03 03:37 UTC, udi-speedb commented on include/rocksdb/write_buffer_manager.h
> +  uint64_t CalcNewCodedUsageState(size_t new_memory_used,
This could be static is I am not mistaken

2023-04-03 03:37 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +void WriteBufferManager::WBMSetupDelay(uint64_t delay_factor) {
I think you should protect this code with the controllers_map_mutex_ mutex

2023-04-03 03:37 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +  for (auto& wc_and_ref_count : controllers_to_refcount_map_) {
I think you should protect this code with the controllers_map_mutex_ mutex

2023-04-03 03:37 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +  bool last_entry = RemoveFromControllersMap(wc);
Having a separate `RemoveFromControllersMap()` makes sense, but, this is the only place where that method is called, and, I could see a (albeit unlikely) race so I would start the locking at the beginning of this method.
So, I would just put the code of `RemoveFromControllersMap()` here and remove `RemoveFromControllersMap()` altogether to simplify it.

2023-04-03 03:37 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +  }
Please also sanitize max_num_parallel_flushes to 1 if set to 0

2023-04-03 03:37 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +    // TODO: udi - is this not an overflow issue?
Do you mean if max_num_parallel_flushes == 0 or in additional cases?
As for 0, I suggested to add a sanitization above for 0

2023-04-03 03:38 UTC, udi-speedb commented
@Yuval-Ariel Another batch of comment. Again, Please do not push a new commit yet. Thanks

2023-04-03 07:15 UTC, Yuval-Ariel commented on db/column_family.cc
> +  }
theres just the overhead of calculating the factor and rate. and it seems to me a bit misleading for someone reading the code in the WBM and cfs because its not clear that it only sets a delay request when dynamic_delay is true.

2023-04-03 14:19 UTC, udi-speedb commented
I suggest adding a start_delay_percent flag to db_bench to be used when initializing the WBM.

2023-04-03 15:01 UTC, Yuval-Ariel commented on db/column_family.h
> +  WriteController* write_controller_ptr() { return write_controller_.get(); }
sure

2023-04-03 15:04 UTC, Yuval-Ariel commented on db/column_family.cc
> +    column_family_set_->ResetCFRate(this);
added WriteController to ColumnFamilyData and made this a CFDs method. 
also added to dtor

2023-04-03 15:14 UTC, Yuval-Ariel commented on db/column_family.cc
> +  }
WBM always registers and deregisters while CFs only when dynamic_delay is on. 
WBM will silently ignore if WBM's flag of allow_delays_and_stalls is false. 
also need to noop if WC's flag dynamic_delay is false.

2023-04-03 15:14 UTC, Yuval-Ariel commented on db/column_family.cc
> +  }
done

2023-04-03 17:13 UTC, udi-speedb requested changes

2023-04-03 17:14 UTC, udi-speedb commented
@Yuval-Ariel A few more minor comments. **I am not done yet**. 
Please address comments and push a commit with updates following the comments I have given thus far. Thanks

2023-04-04 10:44 UTC, Yuval-Ariel commented on db/column_family.cc
> +    write_controller_->HandleRemoveDelayReq(cfd);
HandleRemoveDelayReq is only called when dynamic_delay is true.

2023-04-04 10:44 UTC, Yuval-Ariel commented on db/column_family.cc
> -  return write_controller->GetDelayToken(UpdateCFRate(id_, write_rate));
done

2023-04-04 10:46 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +// including write_controller.h leads to compilation errors.
removed comment

2023-04-04 10:47 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  static constexpr uint64_t kNoneDelayedWriteFactor = 0U;
done

2023-04-04 10:48 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +    // unsuitable value, sanitizing to Dflt. TODO: add reporting
done

2023-04-04 10:51 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  void TEST_set_memory_usage(size_t mem) { memory_used_.store(mem); }
changed to TEST_reset_memory_usage which simply does - memory_used_.store(0) . to prevent future maluses of this TEST method

2023-04-04 10:54 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +      start_delay_percent_(start_delay_percent),
done

2023-04-04 10:58 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  static constexpr bool kDfltAllowStall = true;
done

2023-04-04 10:59 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  bool allow_delays_and_stalls_;
done

2023-04-04 11:00 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  uint64_t wbm_rate_id_;
removed

2023-04-04 11:00 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  std::pair<UsageState, uint64_t> GetUsageStateInfo() const {
done

2023-04-04 11:06 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  uint16_t TEST_get_start_delay_percent() const { return start_delay_percent_; }
removed the TEST, but regarding the camel case, it seems to me to getters and setters are in snake case. e.g. 
```
  size_t buffer_size() const {
    return buffer_size_.load(std::memory_order_relaxed);
  }
```
which would also be more informative in the sense that the name of the member is in the functions name

2023-04-04 11:15 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +  if (controllers_to_refcount_map_.count(wc)) {
done. stayed with count() ;)

2023-04-04 11:16 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +    controllers_to_refcount_map_[wc]--;
done

2023-04-04 11:16 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  static constexpr uint64_t kWBMId = 0U;
removed

2023-04-04 11:17 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +      done = coded_usage_state_.compare_exchange_weak(old_coded_usage_state,
done

2023-04-04 14:48 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +        UpdateControllerDelayState();
from what i can tell, there is no problem with this synchronization. 
coded_usage_state_ always represents the current state of the WBM delay requirement. In the case of several threads calling UpdateUsageState, if a thread fails to update coded_usage_state_ then it recalculates the new value to store in coded_usage_state_ based on the current memory state of the WBM. 
having UpdateControllerDelayState() use coded_usage_state_ makes the updates always in sync with the current state of the WBM, as opposed to passing new_coded_usage_state and using that.

2023-04-04 14:50 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  uint64_t CalcNewCodedUsageState(size_t new_memory_used,
dont think so, it accesses the member start_delay_percent_

2023-04-04 14:56 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +void WriteBufferManager::WBMSetupDelay(uint64_t delay_factor) {
done

2023-04-04 14:56 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +  for (auto& wc_and_ref_count : controllers_to_refcount_map_) {
done

2023-04-04 15:05 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +  bool last_entry = RemoveFromControllersMap(wc);
HandleRemoveDelayReq (which is called from this func) takes the WriteControllers' map_mu_ so i wanted to avoid taking both mutex's. 
Registering and Deregistering only happens at DB Open so its a very rare occasion and i dont see a race as it is.

2023-04-04 15:06 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +  }
we've agreed to include this in a separate issue. @udi-speedb

2023-04-04 15:06 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +    // TODO: udi - is this not an overflow issue?
done

2023-04-06 18:03 UTC, Yuval-Ariel commented on tools/db_crashtest.py
> +    "allow_wbm_stalls": random.randint(0, 1),
done

2023-04-06 18:06 UTC, Yuval-Ariel commented on tools/db_crashtest.py
> +    "allow_wbm_stalls": random.randint(0, 1),
sure

2023-04-07 05:18 UTC, Yuval-Ariel commented on tools/db_crashtest.py
> +    "allow_wbm_stalls": random.randint(0, 1),
done

2023-04-07 05:21 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  static constexpr uint16_t kDfltStartDelayPercentThreshold = 70U;
i dont see a clear connection between them. one can use either one without the other. lets leave it like that and discuss

2023-04-08 17:24 UTC, Yuval-Ariel commented on tools/db_bench_tool.cc
> +DEFINE_bool(allow_wbm_stalls, true, "Enable WBM write stalls and delays");
done

2023-04-17 05:17 UTC, Yuval-Ariel commented
@udi-speedb  , this is waiting for your review

2023-04-17 05:24 UTC, udi-speedb commented
@Yuval-Ariel - Indeed. Will resume the review soon, once the bulk of the log parser work is over.

2023-04-24 04:59 UTC, udi-speedb requested changes

2023-04-24 04:59 UTC, udi-speedb commented on db/column_family.cc
> +        write_controller_token_.reset();
the wc's stop token may be taken and delay may be active as well. Is that an issue?

2023-04-24 04:59 UTC, udi-speedb commented on db/compaction/compaction_job.cc
>    if (versions_ && versions_->GetColumnFamilySet() &&
Minor - You could obtain the write controller's ptr before the if

2023-04-24 04:59 UTC, udi-speedb commented on include/rocksdb/write_buffer_manager.h
> +  static constexpr uint16_t kDfltStartDelayPercentThreshold = 70U;
Let's discuss with Hilik as he was the one who originally told me these 2 should be related

2023-04-24 04:59 UTC, udi-speedb commented on db/write_controller.cc
> +    if (db_id_to_write_rate_map_.count(db_id)) {
Where did you see it used in unordered_maps for this? I have seen the customary find()

2023-04-24 04:59 UTC, udi-speedb commented on db/write_controller.cc
> +  return cf_map.count(cf_id);
And also same as above

2023-04-24 05:47 UTC, Yuval-Ariel commented on db/write_controller.cc
> +    if (db_id_to_write_rate_map_.count(db_id)) {
unordered set:
db/version_set.h:1352 
db/compaction/compaction_iterator.cc:1233
unordered map:
db/db_impl/db_impl_compaction_flush.cc:3691

2023-04-24 06:24 UTC, Yuval-Ariel commented on db/write_controller.h
>  // All of the methods here (including WriteControllerToken's destructors) need
done

2023-04-24 06:25 UTC, Yuval-Ariel commented on db/write_controller.h
>    bool dynamic_delay_;
done

2023-04-24 06:26 UTC, Yuval-Ariel commented on db/write_controller.cc
> +  // protect
done

2023-04-24 06:27 UTC, Yuval-Ariel commented on db/write_controller.cc
> +  if (id_to_write_rate_map_.size() > 0) {
why?

2023-04-24 06:42 UTC, Yuval-Ariel commented on db/write_controller.h
done

2023-04-24 06:48 UTC, Yuval-Ariel commented on db/db_impl/db_impl.h
done

2023-04-25 05:43 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  void RegisterWriteController(WriteController* wc);
i dont think the WBM should share ownership of the WC

2023-04-25 05:45 UTC, Yuval-Ariel commented on db/column_family.cc
> +        write_controller_token_.reset();
not by the same CF , so no its not an issue. its fine for 1 cf to have a delay requirement and the other cf needs a stop.

2023-04-25 05:47 UTC, Yuval-Ariel commented on db/compaction/compaction_job.cc
>    if (versions_ && versions_->GetColumnFamilySet() &&
this is not our code and i would rather not make unnecessary changes due to the overhead of rebasing

2023-04-27 05:35 UTC, udi-speedb commented on db/write_controller.cc
> +  if (id_to_write_rate_map_.size() > 0) {
Because that is what you are testing (readability), that is what empty() is for, and it will have equal or better performance.

2023-04-27 06:12 UTC, udi-speedb commented on db/column_family.cc
> +        write_controller_token_.reset();
I am aware of that. But, unlike before, one DB may require stopping while another delay, and they are interacting with the WC at the same time, which is different that when the wc is accessed by a single CF, under the DB mutex.

2023-04-27 06:12 UTC, udi-speedb commented on db/compaction/compaction_job.cc
>    if (versions_ && versions_->GetColumnFamilySet() &&
OK.

2023-04-27 06:40 UTC, Yuval-Ariel commented on db/write_controller.cc
> +  if (id_to_write_rate_map_.size() > 0) {
if its only about readability then it seems more readable to ask: "if has elements" rather than "if not no elements" but whatever..

2023-04-27 07:43 UTC, udi-speedb commented on db/column_family.cc
> +        write_controller_token_.reset();
That's a result of the WC being global, not the purpose. To your question, not yet.

2023-04-27 08:02 UTC, udi-speedb commented on db/column_family.cc
> +        write_controller_token_.reset();
Never mind. If I find an issue I will comment.

2023-04-27 08:04 UTC, udi-speedb commented
@Yuval-Ariel - Please push whatever updates you have in a new commit. Thanks

2023-04-27 09:04 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  static constexpr uint16_t kDfltStartDelayPercentThreshold = 70U;
hilik said that ideally we'd like the delays to only start once proactive flushes has increased flush rate to at least 2 flushes running. however, we agreed this should be part of the speedb tuning feature

2023-04-27 10:20 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  void RegisterWriteController(WriteController* wc);
how can it be dangling?   `write_buffer_manager_->RegisterWriteController(write_controller_ptr())` is called in the ctor of ColumnFamilySet when opening the db. the write controller is passed to the ctor as a shared_ptr which means the raw pointer passed will remain valid at least until dtor of ColumnFamilySet

2023-04-27 11:36 UTC, udi-speedb commented on include/rocksdb/write_buffer_manager.h
> +  void RegisterWriteController(WriteController* wc);
if everything works as you have planned, then the pointer will never be dangling.
You do not need assertions if everybody uses the interfaces properly. You don't need smart pointers. You should just write your code carefully, make sure to clean up everything in the correct order, etc.
Why are so many RocksDB entities receive and store shared pointers as members instead of raw pointers? 
Why should the WBM receive the cache as a shared_ptr and not as Cache*?

2023-04-30 09:33 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  void RegisterWriteController(WriteController* wc);
we've decided to pass and store a shared_ptr<WC> while also asserting that WBM cannot hold the last ref.

2023-04-30 16:18 UTC, udi-speedb requested changes

2023-04-30 16:20 UTC, udi-speedb commented
@yuval - I have submitted my last comments.

2023-05-01 11:35 UTC, Yuval-Ariel commented on db/column_family.h
>      return write_controller_;
done

2023-05-01 14:34 UTC, Yuval-Ariel commented on include/rocksdb/write_buffer_manager.h
> +  void RegisterWriteController(WriteController* wc);
done

2023-05-01 14:34 UTC, Yuval-Ariel commented on db/global_write_controller_test.cc
> +}  // namespace
done, insearted in db/db_test_util.h

2023-05-01 14:36 UTC, Yuval-Ariel commented on db/global_write_controller_test.cc
> +          false /*initiate_flushes*/));
since for this unit test i want to test the newly added functionality in separate from the Proactive flushes. will be addressed in #457 .

2023-05-01 14:37 UTC, Yuval-Ariel commented on db/global_write_controller_test.cc
> +  }
not sure what you mean. wheres the dup loop?

2023-05-01 14:40 UTC, Yuval-Ariel commented on db/global_write_controller_test.cc
>    Options options = CurrentOptions();
thats what this test (TestGetMinRate) does. am i missing something?

2023-05-01 15:03 UTC, Yuval-Ariel commented on db/global_write_controller_test.cc
> +  }
also not sure what you mean. theres a change, and then we're checking the state. 
you want something like 
```
bool CheckState(int num_dbs, bool assert_false_or_true, bool is_write_delayed_or_stopped)
```
instead of:
```
 for (int i = 0; i < num_dbs; i++) {
    ASSERT_TRUE(IsDbWriteDelayed(dbimpls_[i]));
  }
```

2023-05-01 15:05 UTC, Yuval-Ariel commented on db/write_controller.h
>    // Prerequisite: DB mutex held.
NeedsDelay() returns true only if total_delayed_.load() > 0 not if total_stopped_.load() > 0

2023-05-03 05:24 UTC, Yuval-Ariel commented
thanks @udi-speedb , i've pushed the fixes in the last commit. plz review before i rebase on 8.1.1

2023-05-08 04:43 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +    std::shared_ptr<WriteController> wc) {
You are searching the unordered map 5 times below because you are not using find()

2023-05-08 04:52 UTC, udi-speedb requested changes

2023-05-08 04:52 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +    std::shared_ptr<WriteController> wc) {
You are searching the unordered map 5 times below because you are not using find()

2023-05-08 04:52 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +    assert(wc_and_ref_count.first.unique() == false);
Any reason not to get the WC* and use it as you did in WBMSetupDelay?

2023-05-08 04:52 UTC, udi-speedb commented on memtable/write_buffer_manager.cc
> +    // the last ref to the WC.
The comment accurately explains what the code does, but, IMO it's more improtant to explain why having the WBM hold the last reference is a bug (the justification for the assertion)

2023-05-08 06:39 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +    assert(wc_and_ref_count.first.unique() == false);
done

2023-05-08 06:45 UTC, Yuval-Ariel commented on memtable/write_buffer_manager.cc
> +    // the last ref to the WC.
expanded with:
" since holding the last ref means that the last DB that was using the WC has destructed and using this WC is no longer valid. "

2023-05-08 08:48 UTC, Yuval-Ariel commented
@udi-speedb , ready for review. there will be another review after the rebase

2023-05-08 09:05 UTC, udi-speedb submitted a review, later dismissed

2023-05-10 12:05 UTC, Yuval-Ariel commented
following unit tests fail:
```
     515 ms: /__w/speedb/speedb/compaction_job_test CompactionJobIOPriorityTest.WriteControllerStateDelayed
     470 ms: /__w/speedb/speedb/compaction_job_test CompactionJobIOPriorityTest.GetRateLimiterPriority
     492 ms: /__w/speedb/speedb/db_test DBTest.SkipDelay
     505 ms: /__w/speedb/speedb/db_test DBTest.MixedSlowdownOptions
     496 ms: /__w/speedb/speedb/db_test DBTest.MixedSlowdownOptionsInQueue
     255 ms: /__w/speedb/speedb/flush_job_test FlushJobTest.GetRateLimiterPriorityForWrite
     301 ms: /__w/speedb/speedb/write_controller_test DynamicWC/WriteControllerTest.BasicAPI/1
     312 ms: /__w/speedb/speedb/write_controller_test DynamicWC/WriteControllerTest.StartFilled/1
     303 ms: /__w/speedb/speedb/write_controller_test DynamicWC/WriteControllerTest.DebtAccumulation/1
     294 ms: /__w/speedb/speedb/write_controller_test DynamicWC/WriteControllerTest.CreditAccumulation/1
```
probably all because of calls to GetDelayToken() which fails on assertion of use_dynamic_delay==false since that flag is on by default.

2023-05-22 12:46 UTC, erez-speedb commented
@Yuval-Ariel  perf tests were done on the https://github.com/speedb-io/speedb/issues/114 issue.
Whats the difference ?

2023-05-23 13:15 UTC, Yuval-Ariel commented
i've rebased to rsolve conflicts and added to the HISTORY. plz recheck @udi-speedb

2023-05-23 14:07 UTC, udi-speedb approved these changes

2023-05-24 08:40 UTC, Yuval-Ariel commented
rebased once again to resolve conflicts

2023-05-24 12:52 UTC, udi-speedb approved these changes

2023-05-26 08:31 UTC, merged