Introduce a TableMemoryOptions struct
speedb-io/speedb pull request #428
Opened 2023-03-15 21:55 UTC by mrambacher

Add a "TableMemoryOptions" struct to contain the fields that will be used to determine how to pin or cache blocks from an SST file.

This PR is the first step in the CleanMemoryManager/PinnedMemoryManager.  This PR restructures some of the arguments to the Table classes to pass in a TableMemoryOptions (instead of individual fields).  In the next phase, a PinnedMemoryManager will be added to this struct to allow for accounting of the memory in use per column family.

This PR introduces no algorithmic changes.  It is a restructuring to add a new struct/argument to the methods.

2023-03-30 04:22 UTC, udi-speedb requested changes

2023-03-30 04:22 UTC, udi-speedb commented on db/compaction/compaction_job.cc
> +  // the AddTombstones[ calls will be propagated down to the v1 aggregator.
Seems like the "[" was typed by mistake

2023-03-30 04:22 UTC, udi-speedb commented on db/forward_iterator.cc
> +                                 /*max_file_size_for_l0_meta_pin=*/0, false);
Please add a comment for the false (bottommost level argument)

2023-03-30 04:22 UTC, udi-speedb commented on db/forward_iterator.cc
> +        /*level=*/-1, MaxFileSizeForL0MetaPin(sv_->mutable_cf_options), false);
Same here, please a comment for the false

2023-03-30 04:22 UTC, udi-speedb commented on db/forward_iterator.cc
> +        false);
And here

2023-03-30 04:22 UTC, udi-speedb commented on db/forward_iterator.cc
> +
And...

2023-03-30 04:22 UTC, udi-speedb commented on table/table_builder.h
> +  bool is_bottommost = false;
Wouldn't 3 values (enum) would be preferable - have a "Don't know" value?
I assume that level==-1 should also imply that the is_bottommost is irrelevant.
If it is true that whenever you know the level you also know if it's the bottommost, and apply the "don't know level => don't know is_bottommost", then this is unnecessary (but should be documented)

2023-03-30 04:22 UTC, udi-speedb commented on db/repair.cc
> +                                /*max_file_size_for_l0_meta_pin=*/0, false);
Please add a commnent for the false here as well as in all other cases below.
Why did you choose in this case to explicitly init rather than just default construct?

2023-03-30 04:23 UTC, udi-speedb commented
@mrambacher - This is a first batch of comments. Please address them and also squash all of the commits so I have a single up to date commit to review. Thanks

2023-03-30 09:23 UTC, udi-speedb requested changes

2023-04-30 04:25 UTC, udi-speedb commented
@mrambacher - I understand this PR is abandoned. Please close it.

2023-05-08 04:32 UTC, udi-speedb commented
@mrambacher - Please decide what to do about this PR. Thanks

2023-06-13 15:08 UTC, mrambacher commented
Abandoning this PR as taking a different approach.

2023-06-13 15:08 UTC, closed without merging