Introduce a TablePinningPolicy to control how and when memory is pinned
speedb-io/speedb pull request #459
Opened 2023-04-02 05:42 UTC by mrambacher

This PR adds a TablePinningPolicy to the BlockBasedTableOptions.  This new class is Customizable and can be created from strings.  The class has methods to limit the amount of pin data in the system.

The basic approach is that the unit probes (MayPin) if it believes data is available at the time.  If so, the code does it normal checks and then attempts to pin the new data (PinData).  Once the code is done with the data, UnPinData puts the memory back into the available pool

2023-05-03 14:03 UTC, udi-speedb commented on plugin/speedb/pinning_policy/scoped_pinning_policy_test.cc
> +  // size_t used = 0;
Please remove

2023-05-03 14:09 UTC, udi-speedb commented on plugin/speedb/pinning_policy/scoped_pinning_policy_test.cc
> +      entries.emplace_back(std::move(p));
Wouldn't hurt to assert that p != nullptr on successfull PinData()

2023-05-03 14:12 UTC, udi-speedb commented
@mrambacher - First batch of comments. Haven't finished the review.

2023-05-04 14:19 UTC, udi-speedb commented
@mrambacher - In case it wasn't clear. I am waiting for you to address the comments I have given before continuing my review.

2023-05-14 03:06 UTC, udi-speedb requested changes

2023-05-14 03:06 UTC, udi-speedb commented on plugin/speedb/pinning_policy/scoped_pinning_policy.cc
> +  return CheckPin(tpo, type, size, usage_);
What is MayPin()? used for?
And, it should be clear to the users that they MayPin() may return true but actual pinning may still fail.

2023-05-31 01:34 UTC, udi-speedb approved these changes

2023-05-31 09:58 UTC, mrambacher commented on include/rocksdb/table.h
> +  // EXPERIMENTAL
> Is it valid to mark it as experimental? What will be the behaviour when not specifiying a pinning policy? Or is experminetal referring to policies that are not the default such as ours?

Experimental means that the interface is may change

2023-05-31 10:02 UTC, mrambacher commented on plugin/speedb/pinning_policy/scoped_pinning_policy.h
> +  static const char* kName() { return "ScopedPinningOptions"; }
> I think this is not in use. Should it remain?

It is used implicitly by RegisterOptions

2023-05-31 10:10 UTC, mrambacher commented on table/block_based/table_pinning_policy.h
> +  size_t max_file_size_for_l0_meta_pin = 0;
> Don't we want to add any additional options that will allow us finer control in our pinning policies? They may be default initialized to some harmless values for rocksdb pinning policy.

What other options would you like to see/use?  These are the ones required by the Speedb and RocksDB pinning policies.  If there are others, I can add them now or they can be added in the future.

2023-05-31 10:11 UTC, mrambacher commented on table/block_based/table_pinning_policy.h
> +  static const uint8_t kTopLevel = 1;
> Why aren't these in an enum class of uint8_t size?

They could be an enum.  I thought there would be an arbitrary set of them as we got more of a MemoryManager model and that they may not be known at compile time.

2023-06-06 04:47 UTC, udi-speedb approved these changes

2023-06-11 13:07 UTC, erez-speedb commented
build failed 
CC       plugin/speedb/speedb_registry.o
 CC       plugin/speedb/memtable/hash_spd_rep.o
 CC       plugin/speedb/paired_filter/speedb_paired_bloom.o
 CC       plugin/speedb/paired_filter/speedb_paired_bloom_internal.o
 CC       plugin/speedb/pinning_policy/scoped_pinning_policy.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/concurrent_tree.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/keyrange.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/locktree.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/manager.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/range_buffer.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/treenode.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/txnid_set.o
 CC       utilities/transactions/lock/range/range_tree/lib/locktree/wfg.o
plugin/speedb/pinning_policy/[scoped_pinning_policy.cc](http://scoped_pinning_policy.cc/): In member function ‘virtual bool rocksdb::ScopedPinningPolicy::CheckPin(const rocksdb::TablePinningOptions&, uint8_t, size_t, size_t) const’:
plugin/speedb/pinning_policy/[scoped_pinning_policy.cc:56](http://scoped_pinning_policy.cc:56/):48: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
  56 |   if (tpo.is_bottom && options_.bottom_percent >= 0) {
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~^~~~
plugin/speedb/pinning_policy/[scoped_pinning_policy.cc:60](http://scoped_pinning_policy.cc:60/):52: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
  60 |   } else if (tpo.level > 0 && options_.mid_percent >= 0) {
     |                               ~~~~~~~~~~~~~~~~~~~~~^~~~
 CC       utilities/transactions/lock/range/range_tree/lib/standalone_port.o
 CC       utilities/transactions/lock/range/range_tree/lib/util/dbt.o
 CC       utilities/transactions/lock/range/range_tree/lib/util/memarena.o
 CC       utilities/transactions/lock/range/range_tree/range_tree_lock_manager.o
 CC       utilities/transactions/lock/range/range_tree/range_tree_lock_tracker.o
cc1plus: all warnings being treated as errors
make: *** [Makefile:2418: plugin/speedb/pinning_policy/scoped_pinning_policy.o] Error 1

2023-06-13 01:59 UTC, udi-speedb approved these changes

2023-06-21 07:07 UTC, Yuval-Ariel commented
blocked until https://github.com/speedb-io/speedb/issues/573 is fixed @maxb-io FYI

2023-06-25 08:06 UTC, udi-speedb approved these changes

2023-07-03 12:56 UTC, Yuval-Ariel approved these changes

2023-07-03 13:00 UTC, Yuval-Ariel commented
@mrambacher plz also add to the HISTORY.md file

2023-07-04 07:29 UTC, Yuval-Ariel commented
https://github.com/speedb-io/speedb/actions/runs/5444728254/jobs/9904106132#step:6:571

==15027==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x606000010398 at pc 0x7f21e95a2c2e bp 0x7f21dcdb9f20 sp 0x7f21dcdb9f10
WRITE of size 8 at 0x606000010398 thread T6
    #0 0x7f21e95a2c2d in std::__atomic_base<unsigned long>::operator+=(unsigned long) /usr/include/c++/7/bits/atomic_base.h:312
    #1 0x7f21e95a2c2d in rocksdb::RecordingPinningPolicy::RecordPinned(int, unsigned char, unsigned long, bool) table/block_based/table_pinning_policy.cc:145
    #2 0x7f21e95a2e92 in rocksdb::RecordingPinningPolicy::PinData(rocksdb::TablePinningOptions const&, unsigned char, unsigned long, std::unique_ptr<rocksdb::PinnedEntry, std::default_delete<rocksdb::PinnedEntry> >*) table/block_based/table_pinning_policy.cc:126
    #3 0x7f21e959030e in rocksdb::PartitionIndexReader::Create(rocksdb::BlockBasedTable const*, rocksdb::ReadOptions const&, rocksdb::TablePinningOptions const&, rocksdb::FilePrefetchBuffer*, bool, bool, bool, rocksdb::BlockCacheLookupContext*,

2023-07-16 12:01 UTC, Yuval-Ariel commented on db_stress_tool/db_stress_gflags.cc
> +DEFINE_string(pinning_policy, "", "URI for registry TablePinningPolicy");
plz also add the URIs that exist to tools/db_crashtest.py so that the stress test will use this feature

2023-07-23 06:31 UTC, Yuval-Ariel requested changes
remove foo file.

2023-07-24 06:02 UTC, Yuval-Ariel commented
failed unit tests:
FAILED TESTS (1/11819):
     752 ms: /__w/speedb/speedb/options_settable_test OptionsSettableTest.BlockBasedTableOptionsAllFieldsSettable

2023-07-24 11:58 UTC, Yuval-Ariel approved these changes

2023-08-02 06:26 UTC, merged