SPDB-702: Avoid unnecessary blocking io
speedb-io/speedb pull request #5
Opened 2022-06-07 18:10 UTC by AmnonHanuhov

`avoid_unnecessary_blocking_io` is an option in rocksdb that if set to `true`, allows working threads
to avoid doing unnecessary and long-latency operations on the “hot path” and instead schedule
background jobs to do them. We have seen improvements in compaction latency when this option
was set to `true`, due to the fact that obsolete files were deleted in a separate background
job, instead of being deleted as part of the compaction job.

Signed-off-by: Amnon Hanuhov <AmnonSWE@gmail.com>

2022-08-19 17:50 UTC, AmnonHanuhov commented
All unit tests have passed on my local machine. @isaac-io and I have decided to drop the commit changing the priority of the purges from this PR (as it causes several unit tests to fail) and it will have its own dedicated PR.

2022-08-21 07:04 UTC, isaac-io commented
> [...] have decided to drop the commit changing the priority of the purges from this PR (as it causes several unit tests to fail) and it will have its own dedicated PR.

This PR does require it though in order to avoid using up a high priority thread and hindering flushes, especially with the `DeleteFile()` changes. Please open another PR based on the respective issue (#34) and let's put this one on hold until the other it gets merged.

2022-09-21 08:31 UTC, isaac-io requested changes

2022-10-19 21:54 UTC, isaac-io commented
@AmnonHanuhov I ran the test suite to be sure before approval and I see that the following two tests get stuck:

* `DBCompactionTest.BGCompactionsAllowed` from `db_compaction_test`
* `DBTest2.CompactionOnBottomPriorityWithListener` from `db_test2`

Please take a look at them before I approve.

2022-10-20 05:40 UTC, AmnonHanuhov commented
> @AmnonHanuhov I ran the test suite to be sure before approval and I see that the following two tests get stuck:
> 
> * `DBCompactionTest.BGCompactionsAllowed` from `db_compaction_test`
> * `DBTest2.CompactionOnBottomPriorityWithListener` from `db_test2`
> 
> Please take a look at them before I approve.

👍🏻 I’m on it

2022-10-22 16:21 UTC, AmnonHanuhov commented
> @AmnonHanuhov I ran the test suite to be sure before approval and I see that the following two tests get stuck:
> 
> * `DBCompactionTest.BGCompactionsAllowed` from `db_compaction_test`
> * `DBTest2.CompactionOnBottomPriorityWithListener` from `db_test2`
> 
> Please take a look at them before I approve.

Fixed `db_compaction_test`, it seems that `db_test2` doesn't fail on my machine (I ran the test separately as well as `make check`), please try to run it again (just make sure to pull the recent changes to this branch first).
However, while running `make check` I have noticed that `DeleteFileTest.BackgroundPurgeCopyOptions` from `deletefile_test` fails, on the main branch too. Looks like something was merged to the main branch recently that made this test fail, so this shouldn't be a blocker to this PR.

2022-10-23 08:26 UTC, isaac-io commented
> [...] However, while running `make check` I have noticed that `DeleteFileTest.BackgroundPurgeCopyOptions` from `deletefile_test` fails, on the main branch too. Looks like something was merged to the main branch recently that made this test fail, so this shouldn't be a blocker to this PR.

I'm not seeing this on my machine:

```
$ ./deletefile_test --gtest_filter=DeleteFileTest.BackgroundPurgeCopyOptions
Note: Google Test filter = DeleteFileTest.BackgroundPurgeCopyOptions
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DeleteFileTest
[ RUN      ] DeleteFileTest.BackgroundPurgeCopyOptions
[       OK ] DeleteFileTest.BackgroundPurgeCopyOptions (3792 ms)
[----------] 1 test from DeleteFileTest (3792 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3792 ms total)
[  PASSED  ] 1 test.
$ git log -1
commit 2868d108c74f5675632f3787800ff2c44c74bb80 (HEAD -> main, origin/main, origin/HEAD)
Author: Isaac Garzon <isaac@speedb.io>
Date:   Wed Oct 19 18:07:42 2022 +0300

    options: change the default value for compaction threads to 8 (#169)

    This is done through the deprecated `max_background_compactions` option,
    which overrides `max_background_jobs`, so in order to avoid having an
    adverse effect on users who set `max_background_jobs` to a high value
    we try to detect that case and shift back to the user's choice in case
    there are enough background jobs to be enough for both flushes and
    compactions.
```

Can you post the failure that you're seeing?

2022-10-23 08:45 UTC, isaac-io requested changes

2022-10-23 08:45 UTC, isaac-io commented on db/db_impl/db_impl_open.cc
> +  }
Can you add a comment explaining why this is needed?

2022-10-23 08:45 UTC, isaac-io commented on env/fs_posix.cc
> +    SetFD_CLOEXEC(fd, nullptr);
Note that `fd` can be `-1` at this point due to `ELOOP`.

2022-10-23 10:18 UTC, isaac-io commented
As for the `db_test2` hang that I observed, it can be easily reproduced with the following loop, especially if there's a lot of activity on the machine (such as `make check` running in parallel):

```
while ./db_test2 --gtest_filter=DBTest2.CompactionOnBottomPriorityWithListener; do sleep 1; done
```

Investigating with gdb leads to the following:

```
$ pgrep -af db_test2
252963 ./db_test2 --gtest_filter=DBTest2.CompactionOnBottomPriorityWithListener
$ sudo gdb -p 252963
[...]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f676cc9c4b6 in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f676cc9c4b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007f676cc9ecd0 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007f676e8f870e in rocksdb::port::CondVar::Wait (this=0x558ca96345a0) at /home/isaac/projects/speedb-io/port/port_posix.cc:122
#3  0x00007f676e4c90e4 in rocksdb::InstrumentedCondVar::WaitInternal (this=0x558ca96345a0) at /home/isaac/projects/speedb-io/monitoring/instrumented_mutex.cc:52
#4  0x00007f676e4c907d in rocksdb::InstrumentedCondVar::Wait (this=0x558ca96345a0) at /home/isaac/projects/speedb-io/monitoring/instrumented_mutex.cc:45
#5  0x00007f676e1d5a47 in rocksdb::DBImpl::CloseHelper (this=0x558ca9633b00) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:556
#6  0x00007f676e1d69ff in rocksdb::DBImpl::~DBImpl (this=0x558ca9633b00, __in_chrg=<optimized out>) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:733
#7  0x00007f676e1d6e64 in rocksdb::DBImpl::~DBImpl (this=0x558ca9633b00, __in_chrg=<optimized out>) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:736
#8  0x0000558ca7be9b77 in rocksdb::DBTestBase::Close (this=0x558ca962acd0) at /home/isaac/projects/speedb-io/db/db_test_util.cc:678
#9  0x0000558ca7be9d74 in rocksdb::DBTestBase::Destroy (this=0x558ca962acd0, options=..., delete_cf_paths=false) at /home/isaac/projects/speedb-io/db/db_test_util.cc:698
#10 0x0000558ca7be9c29 in rocksdb::DBTestBase::DestroyAndReopen (this=0x558ca962acd0, options=...) at /home/isaac/projects/speedb-io/db/db_test_util.cc:684
#11 0x0000558ca7acfeeb in rocksdb::DBTest2_CompactionOnBottomPriorityWithListener_Test::TestBody (this=0x558ca962acd0) at /home/isaac/projects/speedb-io/db/db_test2.cc:3574
[...]
(gdb) up 5
#5  0x00007f676e1d5a47 in rocksdb::DBImpl::CloseHelper (this=0x558ca9633b00) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:556
556	    bg_cv_.Wait();
```

Looking at the code, this is a loop that waits for background jobs to complete before closing:

```c++
  // Wait for background work to finish
  while (bg_bottom_compaction_scheduled_ || bg_compaction_scheduled_ ||
         bg_flush_scheduled_ || bg_purge_scheduled_ ||
         pending_purge_obsolete_files_ ||
         error_handler_.IsRecoveryInProgress()) {
    TEST_SYNC_POINT("DBImpl::~DBImpl:WaitJob");
    bg_cv_.Wait();
  }
```

Why do we have background jobs that haven't completed? A hint can be found at the beginning of the test:

```c++
  env_->SetBackgroundThreads(0, Env::Priority::HIGH);
  env_->SetBackgroundThreads(0, Env::Priority::LOW);
  env_->SetBackgroundThreads(1, Env::Priority::BOTTOM);
```

So we only have available threads in the `BOTTOM` pool. This makes sense as the test is named `CompactionOnBottomPriorityWithListener`, so it's specifically looking for compactions scheduled in the `BOTTOM` pool. 

Since this is a new DB and no data was written yet (the backtrace above shows that this is called from `DestroyAndReopen()`, before the test does anything with the DB), there shouldn't be any compactions or other tasks scheduled, so what's going on here?

```
(gdb) p *env_
$1 = {<rocksdb::Customizable> = {<rocksdb::Configurable> = {_vptr.Configurable = 0x558ca7d43fb0 <vtable for rocksdb::SpecialEnv+16>, options_ = std::vector of length 1, capacity 1 = {{name = "",
          opt_ptr = 0x558ca962ec38, type_map = 0x7f676ee36aa0 <rocksdb::(anonymous namespace)::env_wrapper_type_info>}}}, <No data fields>}, thread_status_updater_ = 0x0,
    file_system_ = std::shared_ptr<rocksdb::FileSystem> (use count 11, weak count 0) = {get() = 0x558ca961c630}, system_clock_ = std::shared_ptr<rocksdb::SystemClock> (use count 2, weak count 0) = {get() = 0x558ca961dfb0},
  static kMaxHostNameLen = 256}
(gdb) p ((rocksdb::EnvWrapper*)env_)->target_
$2 = {env = 0x7f676ee3d6c0 <rocksdb::Env::Default()::default_env>, guard = std::shared_ptr<rocksdb::Env> (empty) = {get() = 0x0}}
(gdb) p ((rocksdb::EnvWrapper*)env_)->target_.env
$3 = (rocksdb::Env *) 0x7f676ee3d6c0 <rocksdb::Env::Default()::default_env>
(gdb) p rocksdb::Env::Default()::default_env
$7 = {<rocksdb::CompositeEnv> = {<rocksdb::Env> = {<rocksdb::Customizable> = {<rocksdb::Configurable> = {_vptr.Configurable = 0x7f676edb0c88 <vtable for rocksdb::(anonymous namespace)::PosixEnv+16>,
          options_ = std::vector of length 0, capacity 0}, <No data fields>}, thread_status_updater_ = 0x558ca962ce10, file_system_ = warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<rocksdb::(anonymous namespace)::PosixFileSystem*, rocksdb::FileSystem::Default()::{lambda(rocksdb::(anonymous namespace)::PosixFileSystem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<rocksdb::(anonymous namespace)::PosixFileSystem*, rocksdb::FileSystem::Default()::{lambda(rocksdb::(anonymous namespace)::PosixFileSystem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<rocksdb::FileSystem> (use count 2, weak count 0) = {
        get() = 0x7f676ee3dd20 <rocksdb::FileSystem::Default()::default_fs>}, system_clock_ = std::shared_ptr<rocksdb::SystemClock> (use count 3, weak count 0) = {get() = 0x558ca960d6b0},
      static kMaxHostNameLen = 256}, <No data fields>}, thread_pools_storage_ = std::vector of length 4, capacity 4 = {{<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca95f8d80}}, {<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c540}}, {<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c830}}, {<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962cb20}}}, mu_storage_ = {__data = {__lock = 0,
      __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0},
  threads_to_join_storage_ = std::vector of length 0, capacity 0, allow_non_owner_access_storage_ = true, thread_pools_ = std::vector of length 4, capacity 4 = {{<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca95f8d80}}, {<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c540}}, {<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c830}}, {<rocksdb::ThreadPool> = {
        _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962cb20}}}, mu_ = @0x7f676ee3d720,
  threads_to_join_ = std::vector of length 0, capacity 0, allow_non_owner_access_ = @0x7f676ee3d760}
```

Let's check each of the pools, starting with `BOTTOM`, and going up to `LOW [...]

2022-10-23 18:32 UTC, AmnonHanuhov commented on env/fs_posix.cc
> +    SetFD_CLOEXEC(fd, nullptr);
What would we want to return if that is the case?

2022-10-23 18:32 UTC, AmnonHanuhov commented
> As for the `db_test2` hang that I observed, it can be easily reproduced with the following loop, especially if there's a lot of activity on the machine (such as `make check` running in parallel):
> 
> ```
> while ./db_test2 --gtest_filter=DBTest2.CompactionOnBottomPriorityWithListener; do sleep 1; done
> ```
> 
> Investigating with gdb leads to the following:
> 
> ```
> $ pgrep -af db_test2
> 252963 ./db_test2 --gtest_filter=DBTest2.CompactionOnBottomPriorityWithListener
> $ sudo gdb -p 252963
> [...]
> Using host libthread_db library "/usr/lib/libthread_db.so.1".
> 0x00007f676cc9c4b6 in ?? () from /usr/lib/libc.so.6
> (gdb) bt
> #0  0x00007f676cc9c4b6 in ?? () from /usr/lib/libc.so.6
> #1  0x00007f676cc9ecd0 in pthread_cond_wait () from /usr/lib/libc.so.6
> #2  0x00007f676e8f870e in rocksdb::port::CondVar::Wait (this=0x558ca96345a0) at /home/isaac/projects/speedb-io/port/port_posix.cc:122
> #3  0x00007f676e4c90e4 in rocksdb::InstrumentedCondVar::WaitInternal (this=0x558ca96345a0) at /home/isaac/projects/speedb-io/monitoring/instrumented_mutex.cc:52
> #4  0x00007f676e4c907d in rocksdb::InstrumentedCondVar::Wait (this=0x558ca96345a0) at /home/isaac/projects/speedb-io/monitoring/instrumented_mutex.cc:45
> #5  0x00007f676e1d5a47 in rocksdb::DBImpl::CloseHelper (this=0x558ca9633b00) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:556
> #6  0x00007f676e1d69ff in rocksdb::DBImpl::~DBImpl (this=0x558ca9633b00, __in_chrg=<optimized out>) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:733
> #7  0x00007f676e1d6e64 in rocksdb::DBImpl::~DBImpl (this=0x558ca9633b00, __in_chrg=<optimized out>) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:736
> #8  0x0000558ca7be9b77 in rocksdb::DBTestBase::Close (this=0x558ca962acd0) at /home/isaac/projects/speedb-io/db/db_test_util.cc:678
> #9  0x0000558ca7be9d74 in rocksdb::DBTestBase::Destroy (this=0x558ca962acd0, options=..., delete_cf_paths=false) at /home/isaac/projects/speedb-io/db/db_test_util.cc:698
> #10 0x0000558ca7be9c29 in rocksdb::DBTestBase::DestroyAndReopen (this=0x558ca962acd0, options=...) at /home/isaac/projects/speedb-io/db/db_test_util.cc:684
> #11 0x0000558ca7acfeeb in rocksdb::DBTest2_CompactionOnBottomPriorityWithListener_Test::TestBody (this=0x558ca962acd0) at /home/isaac/projects/speedb-io/db/db_test2.cc:3574
> [...]
> (gdb) up 5
> #5  0x00007f676e1d5a47 in rocksdb::DBImpl::CloseHelper (this=0x558ca9633b00) at /home/isaac/projects/speedb-io/db/db_impl/db_impl.cc:556
> 556	    bg_cv_.Wait();
> ```
> 
> Looking at the code, this is a loop that waits for background jobs to complete before closing:
> 
> ```c++
>   // Wait for background work to finish
>   while (bg_bottom_compaction_scheduled_ || bg_compaction_scheduled_ ||
>          bg_flush_scheduled_ || bg_purge_scheduled_ ||
>          pending_purge_obsolete_files_ ||
>          error_handler_.IsRecoveryInProgress()) {
>     TEST_SYNC_POINT("DBImpl::~DBImpl:WaitJob");
>     bg_cv_.Wait();
>   }
> ```
> 
> Why do we have background jobs that haven't completed? A hint can be found at the beginning of the test:
> 
> ```c++
>   env_->SetBackgroundThreads(0, Env::Priority::HIGH);
>   env_->SetBackgroundThreads(0, Env::Priority::LOW);
>   env_->SetBackgroundThreads(1, Env::Priority::BOTTOM);
> ```
> 
> So we only have available threads in the `BOTTOM` pool. This makes sense as the test is named `CompactionOnBottomPriorityWithListener`, so it's specifically looking for compactions scheduled in the `BOTTOM` pool.
> 
> Since this is a new DB and no data was written yet (the backtrace above shows that this is called from `DestroyAndReopen()`, before the test does anything with the DB), there shouldn't be any compactions or other tasks scheduled, so what's going on here?
> 
> ```
> (gdb) p *env_
> $1 = {<rocksdb::Customizable> = {<rocksdb::Configurable> = {_vptr.Configurable = 0x558ca7d43fb0 <vtable for rocksdb::SpecialEnv+16>, options_ = std::vector of length 1, capacity 1 = {{name = "",
>           opt_ptr = 0x558ca962ec38, type_map = 0x7f676ee36aa0 <rocksdb::(anonymous namespace)::env_wrapper_type_info>}}}, <No data fields>}, thread_status_updater_ = 0x0,
>     file_system_ = std::shared_ptr<rocksdb::FileSystem> (use count 11, weak count 0) = {get() = 0x558ca961c630}, system_clock_ = std::shared_ptr<rocksdb::SystemClock> (use count 2, weak count 0) = {get() = 0x558ca961dfb0},
>   static kMaxHostNameLen = 256}
> (gdb) p ((rocksdb::EnvWrapper*)env_)->target_
> $2 = {env = 0x7f676ee3d6c0 <rocksdb::Env::Default()::default_env>, guard = std::shared_ptr<rocksdb::Env> (empty) = {get() = 0x0}}
> (gdb) p ((rocksdb::EnvWrapper*)env_)->target_.env
> $3 = (rocksdb::Env *) 0x7f676ee3d6c0 <rocksdb::Env::Default()::default_env>
> (gdb) p rocksdb::Env::Default()::default_env
> $7 = {<rocksdb::CompositeEnv> = {<rocksdb::Env> = {<rocksdb::Customizable> = {<rocksdb::Configurable> = {_vptr.Configurable = 0x7f676edb0c88 <vtable for rocksdb::(anonymous namespace)::PosixEnv+16>,
>           options_ = std::vector of length 0, capacity 0}, <No data fields>}, thread_status_updater_ = 0x558ca962ce10, file_system_ = warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<rocksdb::(anonymous namespace)::PosixFileSystem*, rocksdb::FileSystem::Default()::{lambda(rocksdb::(anonymous namespace)::PosixFileSystem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
> warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<rocksdb::(anonymous namespace)::PosixFileSystem*, rocksdb::FileSystem::Default()::{lambda(rocksdb::(anonymous namespace)::PosixFileSystem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
> std::shared_ptr<rocksdb::FileSystem> (use count 2, weak count 0) = {
>         get() = 0x7f676ee3dd20 <rocksdb::FileSystem::Default()::default_fs>}, system_clock_ = std::shared_ptr<rocksdb::SystemClock> (use count 3, weak count 0) = {get() = 0x558ca960d6b0},
>       static kMaxHostNameLen = 256}, <No data fields>}, thread_pools_storage_ = std::vector of length 4, capacity 4 = {{<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca95f8d80}}, {<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c540}}, {<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c830}}, {<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962cb20}}}, mu_storage_ = {__data = {__lock = 0,
>       __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0},
>   threads_to_join_storage_ = std::vector of length 0, capacity 0, allow_non_owner_access_storage_ = true, thread_pools_ = std::vector of length 4, capacity 4 = {{<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca95f8d80}}, {<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c540}}, {<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962c830}}, {<rocksdb::ThreadPool> = {
>         _vptr.ThreadPool = 0x7f676eda4348 <vtable for rocksdb::ThreadPoolImpl+16>}, impl_ = std::unique_ptr<rocksdb::ThreadPoolImpl::Impl> = {get() = 0x558ca962cb20}}}, mu_ = @0x7f676ee3d720,
>   thread [...]

2022-10-24 06:47 UTC, isaac-io commented on env/fs_posix.cc
> +    SetFD_CLOEXEC(fd, nullptr);
Nothing. We're only opening the file to keep it from getting immediately deleted. If we fail due to `ELOOP`, that's not really an issue. We'll simply unlink without having the file open and pay the price for immediate deletion.

2022-10-24 06:49 UTC, isaac-io commented on env/fs_posix.cc
> +      }
We need to unlink even if we failed to open the file, because we only open the file for truncation as an optimisation. We shouldn't fail where this function didn't fail before (which is also why we probably shouldn't return an error at all if we failed to open, and only `SetFD_CLOEXEC(fd, nullptr)` when we succeeded opening.

2022-10-25 06:24 UTC, isaac-io approved these changes
I left a minor comment, but other than that LGTM. Note that we still need a `db_bench` scenario that would show the performance improvement before we can merge this though. Please work with @hilikspdb on such a scenario and post here so @erez-speedb could check that.

2022-10-25 06:24 UTC, isaac-io commented on env/fs_posix.cc
> +      SetFD_CLOEXEC(fd, nullptr);
Setting `CLOEXEC` is something that should be done as close to the successful `open()` call as possible (before trying to `unlink()`) in order to avoid the case where our process forks and the child is inheriting this file handle. This is especially relevant here, because holding the handle open would prevent the system from actually freeing up the storage used.

The best way is to simply add another check for `fd >= 0` right after the `open()` loop and do it there.

2022-10-25 07:43 UTC, hilikspdb commented
Since this is merely a change in the option the changes we have done to
support this change must be part of the version . The question if to set it
to true or false by default and this is a minor question....

On Tue, Oct 25, 2022 at 9:24 AM isaac-io ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> I left a minor comment, but other than that LGTM. Note that we still need
> a db_bench scenario that would show the performance improvement before we
> can merge this though. Please work with @hilikspdb
> <https://github.com/hilikspdb> on such a scenario and post here so
> @erez-speedb <https://github.com/erez-speedb> could check that.
> ------------------------------
>
> In env/fs_posix.cc
> <https://github.com/speedb-io/speedb/pull/5#discussion_r1004050841>:
>
> >      IOStatus result;
>      if (unlink(fname.c_str()) != 0) {
> -      result = IOError("while unlink() file", fname, errno);
> +      result = IOError("while unlinking file", fname, errno);
> +    }
> +    if (fd >= 0) {
> +      SetFD_CLOEXEC(fd, nullptr);
>
> Setting CLOEXEC is something that should be done as close to the
> successful open() call as possible (before trying to unlink()) in order
> to avoid the case where our process forks and the child is inheriting this
> file handle. This is especially relevant here, because holding the handle
> open would prevent the system from actually freeing up the storage used.
>
> The best way is to simply add another check for fd >= 0 right after the
> open() loop and do it there.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/speedb-io/speedb/pull/5#pullrequestreview-1154199342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZKTXGC6MFNNUN4LK6LY5C3WE54LVANCNFSM5YD2NMKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-25 13:32 UTC, erez-speedb commented
Performance test need to be added, seek while writing with significant write load (50/50 ?)
In the current list, we run 95% seek.

2022-10-25 13:58 UTC, Yuval-Ariel commented
bare in mind that this ticket also includes #36 . so the testing needs to cover that as well. @AmnonHanuhov how do you suppose these changes could affect the system?

2022-11-16 12:19 UTC, erez-speedb commented
I don't see any gain in either the small obj test
 
<img width="1095" alt="Screenshot 2022-11-16 at 14 18 53" src="https://user-images.githubusercontent.com/106964746/202178909-a1406617-9ae9-482f-bfd3-5d6c6ea38766.png">

O the large obj
<img width="1120" alt="Screenshot 2022-11-16 at 14 15 55" src="https://user-images.githubusercontent.com/106964746/202178674-c3e71295-9d6f-4ee3-807c-cc28631ba78a.png">

2022-12-27 12:31 UTC, Guyme commented
Shows no value, abandoned.

2022-12-27 12:31 UTC, closed without merging