Enable speedb features rebase
speedb-io/speedb pull request #543
Opened 2023-06-07 17:18 UTC by RoyBenMoshe

2023-06-08 02:14 UTC, udi-speedb commented
Running make_format on the branch still has formatting issues

2023-06-08 08:14 UTC, udi-speedb requested changes

2023-06-08 08:14 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  std::cout << "0" << std::endl;
Best to print something more meaningful

2023-06-08 08:14 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  op2.EnableSpeedbFeatures(&so);
The important comments that should be part of this code are comments that emphasize the aspectes of the new feature

2023-06-08 08:14 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  // atomically apply a set of updates
Why are all the db operations part of this example? 
What are they contributing to the specific aspects of the feature?

2023-06-08 08:14 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  }
Unless I have missed this, where is the code that demonstrates all of the capabilities the feature allows / exposes?

2023-06-08 08:14 UTC, udi-speedb commented
@RoyBenMoshe - An initial batch of comments. Let's discuss

2023-06-08 11:19 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +struct SharedOptionsSpeeDB : public SharedOptions {
done

2023-06-08 11:28 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  // If set and initialized will define the shared recources.
fixed

2023-06-08 11:31 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  int _total_threads = 0;
fixed

2023-06-08 11:40 UTC, udi-speedb commented on include/rocksdb/version.h
> +#define SPEEDB_PATCH 0
Is this supposed to be part of your change?

2023-06-08 11:43 UTC, udi-speedb commented on examples/Makefile
> +CXXFLAGS += -g
You should probably remove this change.

2023-06-08 11:48 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +// use this struct to arrange multiple db shared options
done

2023-06-08 11:55 UTC, udi-speedb commented on options/options.cc
> +    if (s.ok()) {
What is s.ok()==false?
What should we do in this case?
What do we signal the user?

2023-06-08 12:14 UTC, RoyBenMoshe commented on include/rocksdb/version.h
> +#define SPEEDB_PATCH 0
fixed

2023-06-08 12:18 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  Options op1, op2;
done

2023-06-08 12:25 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  op1.EnableSpeedbFeatures(&so);
fixed

2023-06-08 13:19 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  // atomically apply a set of updates
fixed

2023-06-08 14:00 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  std::shared_ptr<SharedOptionsSpeeDB> so =
changed

2023-06-08 14:00 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  op2.EnableSpeedbFeatures(&so);
changed

2023-06-08 14:01 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  }
changed

2023-06-08 15:18 UTC, RoyBenMoshe commented on options/options.cc
> +    if (s.ok()) {
fixed

2023-06-08 15:35 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +struct SharedOptions {
changed

2023-06-08 15:44 UTC, mrambacher commented on examples/enable_speedb_features_example.cc
> +  op1.EnableSpeedbFeatures(so1);
Should this line be before line 45?  How does one know what features Speedb will set?

2023-06-08 15:44 UTC, mrambacher commented on include/rocksdb/options.h
> +struct SpeedbSharedOptions : public SharedOptions {
Personally, I do not see where you are going to want a separate class here, rather than just setting everything in the SharedOptions.  There is no new functionality, only potentially defaults.  Why not just make the Speedb stuff a method in the base class?

2023-06-08 15:44 UTC, mrambacher commented on options/options.cc
> +    Status s = FilterPolicy::CreateFromString(
@udi-speedb I think there is an option that must be set to use the paired bloom filter.  Should it be set here?

2023-06-08 15:44 UTC, mrambacher commented on options/options_test.cc
> +  delete db3;
Does this leave database files around on the file system?  Can we somehow clean them up?

2023-06-08 15:44 UTC, mrambacher commented on options/options_test.cc
> +  ASSERT_OK(db1->DropColumnFamily(cf));
How do you know the CF used any of the features?

2023-06-08 15:49 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +
fixed

2023-06-08 15:52 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  // open DBs that will share the recoureces in the shared options
changed

2023-06-08 15:53 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +// Copyright (c) 2011-present, Facebook, Inc.  All rights reserved.
fixed

2023-06-08 16:45 UTC, RoyBenMoshe commented on options/options_test.cc
> +  delete db3;
fixed

2023-06-08 16:57 UTC, RoyBenMoshe commented on options/options.cc
> +    ConfigOptions config_options;
fixed

2023-06-08 19:47 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +using ROCKSDB_NAMESPACE::DB;
using namespace is not allowed in the CI

2023-06-09 04:35 UTC, RoyBenMoshe commented on options/db_options.h
> +  std::shared_ptr<SharedOptions> shared_options;
fixed

2023-06-09 04:49 UTC, RoyBenMoshe commented on options/options_test.cc
> +  ASSERT_OK(db1->DropColumnFamily(cf));
changed

2023-06-11 04:44 UTC, udi-speedb requested changes

2023-06-11 04:44 UTC, udi-speedb commented on include/rocksdb/options.h
> +  DBOptions* EnableSpeedbFeaturesDB(SpeedbSharedOptions& shared_options);
Same comment as above about the documentation for this function

2023-06-11 04:44 UTC, udi-speedb commented on include/rocksdb/options.h
> +  Options* EnableSpeedbFeatures(SpeedbSharedOptions& shared_options);
And the same here about the documentation (which is even shorted in this one, which is truly the most useful)

2023-06-11 04:44 UTC, udi-speedb commented on include/rocksdb/options.h
> +  size_t write_buffer_size_;
Why is this a member? It is calculated once from in the ctor (initializeSharedOptionsForSpeeDB())?

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +  write_controller.reset(new WriteController(true, delayed_write_rate_));
Please add the meaning of the first parameter: true /* dynamic_delay */

And also here, there is an additional low_pri_rate_bytes_per_sec parameter that I suggest to init explicitly.

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +  write_buffer_manager.reset(new WriteBufferManager(
I suggest we explicitly initialize all of the options of the WBM and not rely on default values for its arguments.

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +      write_buffer_size_, cache /*,  shared_write_controler */));
What does "cache /*, shared_write_controler */ mean?

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +  cache = NewLRUCache(total_ram_size_bytes_);
This function has many parameters (pasted below).
I suggest explicitliy initializing them, even if the values match the defaults.
extern std::shared_ptr<Cache> NewLRUCache(
    size_t capacity, int num_shard_bits = -1,
    bool strict_capacity_limit = false, double high_pri_pool_ratio = 0.5,
    std::shared_ptr<MemoryAllocator> memory_allocator = nullptr,
    bool use_adaptive_mutex = kDefaultToAdaptiveMutex,
    CacheMetadataChargePolicy metadata_charge_policy =
        kDefaultCacheMetadataChargePolicy,
    double low_pri_pool_ratio = 0.0);

2023-06-11 04:44 UTC, udi-speedb commented on include/rocksdb/options.h
> +struct SpeedbSharedOptions : public SharedOptions {
I think this should be a class and not a struct.

2023-06-11 04:44 UTC, udi-speedb commented on include/rocksdb/options.h
> +};
I suggest removing all of the members that we are not explicitly initializing.

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +  write_buffer_manager = shared_options.write_buffer_manager;
Don't you need to init the write controller as well?

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +  db_write_buffer_size =
Why are you not using the value from the WBM (wbm->buffer_size())?

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +  if (shared_options.getDelayedWriteRate() != 0) {
In case our shared obj has the delayed write rate at 0 at this point. Does it mean that we would like to use the user's delayed write rate? 
Is that the requirement?

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +DBOptions* DBOptions::EnableSpeedbFeaturesDB(
What is the requirement regarding overriding shared objects / options that the user has updated before calling our enable feature?
Do we silently override?
Should we abort? Notify to the log? Other?

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +  env = shared_options.env;
I would just leave the env out of this feature for now. We leave it in the Env::Default() anyway.

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +    block_based_table_options.block_cache = shared_options.cache;
I would explicitly set all of the caching related options, even if we set them to their default values. That way it's both explicit and protects agains future changes in the default that may not be the optimal for Speedb.
For example: cache_index_and_filter_blocks_with_high_priority, pin_l0_filter_and_index_blocks_in_cache

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +    std::unique_ptr<MemTableRepFactory> unique;
I suggest to rename "unique" to something more meaningful

2023-06-11 04:44 UTC, udi-speedb commented on options/options.cc
> +    config_options;
Should you have created a default ConfigOptions() to be used in the call to MemTableRepFactory::CreateFromString()?
The best thing (and would also avoid this issue) would be to just write:
MemTableRepFactory::CreateFromString(ConfigOptions(), ...)

2023-06-11 05:02 UTC, udi-speedb commented
@RoyBenMoshe Another batch of comments. I am not  done yet, but will wait with the rest until you have addressed the comments in this batch. Thanks

2023-06-11 06:54 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  DB *db5 = nullptr;
fixed

2023-06-11 06:55 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  // again customize each options file except SpeedbSharedOptiopns members
fixed

2023-06-11 06:56 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  // open DBs that will share the recoureces in the shared options
changed

2023-06-11 06:56 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  // open the databases that sharing the recoureces from shared_options opbject
changed

2023-06-11 07:10 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  db3->DropColumnFamily(cf);
This is important to allow this example to be re-run without having to clean up db3

2023-06-11 07:13 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  size_t write_buffer_size_;
according to the current design, I beleive those calculated values should be kept as long as this object live

2023-06-11 07:19 UTC, RoyBenMoshe commented on options/options.cc
> +  initializeSharedOptionsForSpeeDB();
It might be more flexible design for the future of this struct.

2023-06-11 07:21 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  db3->CreateColumnFamily(cfo3, "new_cf", &cf);
fixed

2023-06-11 07:36 UTC, RoyBenMoshe commented on options/options.cc
> +  initializeSharedOptionsForSpeeDB();
It might be more flexible design for the future of this struct.

2023-06-11 07:37 UTC, RoyBenMoshe commented on options/options.cc
> +      write_buffer_size_, cache /*,  shared_write_controler */));
fixed

2023-06-11 08:10 UTC, RoyBenMoshe commented on options/options.cc
> +    config_options;
fixed

2023-06-11 08:11 UTC, RoyBenMoshe commented on options/options.cc
> +    std::unique_ptr<MemTableRepFactory> unique;
fixed

2023-06-11 08:21 UTC, RoyBenMoshe commented on options/options.cc
> +    Status s = FilterPolicy::CreateFromString(
changed to 10 bpk

2023-06-11 08:37 UTC, RoyBenMoshe commented on options/options.cc
> +  cache = NewLRUCache(total_ram_size_bytes_);
fixed

2023-06-11 08:43 UTC, RoyBenMoshe commented on options/options.cc
> +  write_controller.reset(new WriteController(true, delayed_write_rate_));
fixed

2023-06-11 08:59 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +struct SpeedbSharedOptions : public SharedOptions {
as all the other optins objects here in this section, I chose to keep the same way.

2023-06-11 09:01 UTC, RoyBenMoshe commented on tools/db_bench_tool.cc
> +            "When true use enable all the spdb features");
changed

2023-06-11 09:05 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  // optimized for SpeeDB features, As a starting point for configuring
fixed

2023-06-11 09:09 UTC, RoyBenMoshe commented on options/options.cc
> +  env = shared_options.env;
Maybe now it is Env::Default() anyway, but I think this serves the design guidelines.

2023-06-11 09:59 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +struct SpeedbSharedOptions : public SharedOptions {
user might want to arrange her shared options as today by just using SharedOptions, which includes all the shared_ptrs from DBOptions. SpeedbSharedOptions offer initialization methodolgy for some of the members of SharedOptions(but not all of them) for use as a part of enable SpeeDB features feature, at this point I prefer to keep this speration, maybe in the future it will be more clear with the evoulotion of this feature and it will be a good point to reconsider.

2023-06-11 11:18 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  Options* EnableSpeedbFeatures(SpeedbSharedOptions& shared_options);
changed, link to documentation will be added soon

2023-06-11 11:27 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  DBOptions* EnableSpeedbFeaturesDB(SpeedbSharedOptions& shared_options);
link to doc will be added soon

2023-06-11 11:48 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  // SpeeDB Features, use this function.
link to documentation will be added soon

2023-06-11 11:50 UTC, RoyBenMoshe commented on options/options.cc
> +    Status s = FilterPolicy::CreateFromString(
changed to 10 bpk

2023-06-11 11:57 UTC, RoyBenMoshe commented on options/options.cc
> +    block_based_table_options.block_cache = shared_options.cache;
changed

2023-06-11 12:00 UTC, RoyBenMoshe commented on options/options.cc
> +  write_buffer_manager = shared_options.write_buffer_manager;
fixed

2023-06-11 12:10 UTC, RoyBenMoshe commented on options/options.cc
> +  db_write_buffer_size =
it is not defined yet, it will be defined under this call

2023-06-11 13:07 UTC, RoyBenMoshe commented on options/options.cc
> +  db_write_buffer_size =
changed

2023-06-11 13:08 UTC, RoyBenMoshe commented on options/options.cc
> +  initializeSharedOptionsForSpeeDB();
changed

2023-06-11 13:16 UTC, RoyBenMoshe commented on options/options.cc
> +  write_buffer_manager.reset(new WriteBufferManager(
fixed

2023-06-11 13:21 UTC, RoyBenMoshe commented on options/options.cc
> +DBOptions* DBOptions::EnableSpeedbFeaturesDB(
for now the responsibility of not changing somthing that she is not should to, is on the user.
especially after removing initialize SpeeDB function now the only constructor is initializing the object.

2023-06-11 13:28 UTC, RoyBenMoshe commented on options/options.cc
> +  if (shared_options.getDelayedWriteRate() != 0) {
changed

2023-06-12 03:57 UTC, udi-speedb requested changes

2023-06-12 03:57 UTC, udi-speedb commented on options/options.cc
> +    Status s = FilterPolicy::CreateFromString(
Is 10 what we want? 
I do not know the answer to this question.
What is the reason to set it one way or the other (or anything else)?

2023-06-12 03:57 UTC, udi-speedb commented on options/options.cc
> +    block_based_table_options.metadata_cache_options.unpartitioned_pinning =
Please move them to line 632

2023-06-12 03:57 UTC, udi-speedb commented on options/options.cc
> +    memtable_opt = ":" + std::to_string(0);
Does "0" mean default bucket count?
Assuming it is, please document
And, in general, please add documentation to the values you are assigning to the options or to a group of options so the motivations are documented.

2023-06-12 03:57 UTC, udi-speedb commented on options/options_test.cc
> +}
Please explicitly verify all of the properties that should have been set by the ctor, e.g., write controller, pointers that are not null or should be null, etc.

2023-06-12 03:57 UTC, udi-speedb commented on options/options_test.cc
> +  DB *db1, *db2, *db3;
It may be preferable to have the db-s and options placed in a vector and the code would loop over them

2023-06-12 03:57 UTC, udi-speedb commented on options/options_test.cc
> +  for (auto dbname_ : {"db1", "db2", "db3"}) {
why dbname_ and not dbname?

2023-06-12 03:57 UTC, udi-speedb commented on options/options_test.cc
> +  delete db3;
db.h has a DestroyDB() utility. Are you trying to implement it here?

2023-06-12 03:57 UTC, udi-speedb commented on options/options_test.cc
> +  delete db1;
Same as above. Can't you use db.h's DestroyDB()?

2023-06-12 07:39 UTC, RoyBenMoshe commented on tools/db_bench_tool.cc
> +
I think we can add it in the future

2023-06-12 07:40 UTC, RoyBenMoshe commented on tools/db_bench_tool.cc
> +
fixed

2023-06-12 07:41 UTC, RoyBenMoshe commented on tools/db_bench_tool.cc
> +
cleaned for now

2023-06-12 07:42 UTC, RoyBenMoshe commented on examples/Makefile
>  .PHONY: clean static_lib
fixed

2023-06-12 07:42 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +// Copyright (C) 2022 Speedb Ltd. All rights reserved.
fixed

2023-06-12 07:45 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  // optimized for SpeeDB features, As a starting point for configuring
fixed

2023-06-12 07:46 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  // Use SpeeDB's dynamic delay -
fixed

2023-06-12 07:50 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  void increaseWriteBufferSize(size_t write_buffer_size_addition);
fixed

2023-06-12 07:50 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  void initializeSharedOptionsForSpeeDB();
fixed

2023-06-12 08:07 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +};
this feature is initializing and configuring Speedb features that most of them affect multiple data base case. this struct is a very basic structure to improve the usebilty of configurenig any multiple databases case, Rocksdb or Speedb.
SpeedbSharedOption wrap this struct and will force some of the shared_ptrs by the EnableSpeedbFeatures methodolgy.
At this stage I preffer to keep the speration between the structure for any multiple databases case to the Speedb methodology.

2023-06-12 08:09 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  op1.EnableSpeedbFeatures(so1);
fixed

2023-06-12 08:15 UTC, RoyBenMoshe commented on options/options.cc
> +    size_t delayed_write_rate = 256 * 1024 * 1024) {
fixed

2023-06-12 08:22 UTC, RoyBenMoshe commented on options/options.cc
> +    block_based_table_options.metadata_cache_options.unpartitioned_pinning =
fixed

2023-06-12 08:51 UTC, RoyBenMoshe commented on options/options_test.cc
> +  for (auto dbname_ : {"db1", "db2", "db3"}) {
fixed

2023-06-12 09:18 UTC, RoyBenMoshe commented on options/options_test.cc
> +  DB *db1, *db2, *db3;
I prefer to leave it like this maybe a bit ugly but very simple and clear

2023-06-12 09:22 UTC, RoyBenMoshe commented on options/options_test.cc
> +  delete db3;
changed

2023-06-12 09:23 UTC, RoyBenMoshe commented on options/options_test.cc
> +  delete db1;
changed

2023-06-12 09:23 UTC, RoyBenMoshe commented on options/options.cc
> +DBOptions* DBOptions::EnableSpeedbFeaturesDB(
fixed

2023-06-12 09:31 UTC, RoyBenMoshe commented on options/options.cc
> +void SpeedbSharedOptions::increaseWriteBufferSize(size_t increase_by) {
done

2023-06-12 09:36 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +using ROCKSDB_NAMESPACE::DB;
fixed

2023-06-12 09:40 UTC, RoyBenMoshe commented on options/options.cc
> +  write_buffer_manager = shared_options.write_buffer_manager;
ok,got it

2023-06-12 09:41 UTC, RoyBenMoshe commented on options/options.cc
> +  std::__1::shared_ptr<rocksdb::MemoryAllocator> memory_allocator = nullptr;
fixed

2023-06-12 10:00 UTC, RoyBenMoshe commented on options/options.cc
> +      new WriteBufferManager(initial_write_buffer_size_, cache));
fixed

2023-06-12 10:02 UTC, RoyBenMoshe commented on options/options.cc
> +    Status s = FilterPolicy::CreateFromString(
After a discussion with @hilikspdb this is the value that was chosen as a default value for a wide range of cases.

2023-06-12 10:10 UTC, RoyBenMoshe commented on options/options.cc
> +    memtable_opt = ":" + std::to_string(0);
ocumentation were added

2023-06-12 10:54 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +struct SpeedbSharedOptions : public SharedOptions {
changed

2023-06-13 02:45 UTC, udi-speedb commented
Please update the HISTORY.md as part of the PR as well.

2023-06-13 02:58 UTC, udi-speedb requested changes

2023-06-13 02:58 UTC, udi-speedb commented on include/rocksdb/options.h
> +  // 32
The documentation is good.
Please verify that you are listing all of the applicable options. Also, please make sure you are not listing options that are not handled by the cf part of the feature.

2023-06-13 02:58 UTC, udi-speedb commented on include/rocksdb/options.h
> +  DBOptions* EnableSpeedbFeaturesDB(SpeedbSharedOptions& shared_options);
Same as above (the cf part)

2023-06-13 02:58 UTC, udi-speedb commented on include/rocksdb/options.h
> +// find in  enable_speedb_features_example.cc
I suggest to avoid duplicating the "you should not change: ...." text here as well. I think the information in the EnableXXX() methods is sufficient.
I suggest to keep it to the specific information about this class.

2023-06-13 02:58 UTC, udi-speedb commented on options/options.cc
> +      new WriteBufferManager(initial_write_buffer_size_, cache));
You have prepared the additional wbm's parameters but you are not actually using them in the wbm's ctor.

2023-06-13 02:58 UTC, udi-speedb commented on options/options.cc
> +  int num_shard_bits = -1;
Did you verify with Hilik that he doesn't want to control the number of shard bits and leave it to the existing RocksDB heuristic?

2023-06-13 02:58 UTC, udi-speedb commented on options/options.cc
> +  int initial_write_buffer_size_ = 1;
Please provide a short rationale for the 1 byte size. Why not leave it as 0?

2023-06-13 02:58 UTC, udi-speedb commented on options/options.cc
> +void SpeedbSharedOptions::IncreaseWriteBufferSize(size_t increase_by) {
Please move the documentation for the wbm's size increase per cf here (you have included it elsewhere)

2023-06-13 02:58 UTC, udi-speedb commented on options/options_test.cc
> +  delete db1;
Shouldn't you delete after calling DestroyDB() below?

2023-06-13 02:58 UTC, udi-speedb commented on options/options_test.cc
> +  delete db1;
Same as above. Shouldn't the db be deleted after DestroyDB()?
And please also close the db before deleting it.

2023-06-13 02:58 UTC, udi-speedb commented on options/options_test.cc
> +  ASSERT_OK(DestroyDB("db1", op1));
DestroyDB() allows you to list cf-s instead of dropping / destroying them explicitly

2023-06-13 02:58 UTC, udi-speedb commented on options/options_test.cc
> +
What about all of the other properties of the cf that should have been set by the EnableSpeedbFeaturesCF?

2023-06-13 02:58 UTC, udi-speedb commented on options/options_test.cc
> +              3 * 512 * 1024 * 1024ul);
What about the other properties that are modified by the EnableSpeedbFeatures() call?

2023-06-13 02:58 UTC, udi-speedb commented on options/options_test.cc
> +
What is the use case for the individual EnableSpeedbFeaturesDB()?
When will a user call this method only and not just the EnableSpeedbFeatures()?
Please add a unit test for it.

2023-06-13 02:58 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +        column_families.push_back(
I think you should revert this change. It doesn't compile.

2023-06-13 02:58 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  s = db3->DropColumnFamily(cf);
Why is it important to include the dropping / destroying of the cf in this example?
However, since the db is created on /tmp, I think there is no need for cleanup code as part of the example.
You should nevertheless call Close() before deleting the db*

2023-06-13 02:58 UTC, udi-speedb commented on options/options_test.cc
> +  db1 = nullptr;
Please Close() the db-s before deleting them

2023-06-13 10:02 UTC, RoyBenMoshe commented on tools/db_bench_tool.cc
> +        column_families.push_back(
fixed

2023-06-13 14:21 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +// find in  enable_speedb_features_example.cc
fixed

2023-06-13 14:35 UTC, RoyBenMoshe commented on options/options.cc
> +  int initial_write_buffer_size_ = 1;
fixed

2023-06-13 14:37 UTC, RoyBenMoshe commented on options/options.cc
> +  int num_shard_bits = -1;
yes, verifeid. also for all the other defaults

2023-06-13 14:51 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  // 32
fixed

2023-06-13 14:55 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  DBOptions* EnableSpeedbFeaturesDB(SpeedbSharedOptions& shared_options);
fixed

2023-06-13 14:57 UTC, RoyBenMoshe commented on options/options.cc
> +void SpeedbSharedOptions::IncreaseWriteBufferSize(size_t increase_by) {
I moved it to the relevant code in the EnableSpeedbCF function

2023-06-13 15:12 UTC, RoyBenMoshe commented on options/options_test.cc
> +              3 * 512 * 1024 * 1024ul);
is just calling EnableSpeedbFeaturesDB and EnableSpeedbFeaturesCF

2023-06-13 15:25 UTC, RoyBenMoshe commented on options/options_test.cc
> +  delete db1;
I did it like db_test when db is opened by using a pointer, it first closed and then destroyed.
as I understand from many examples in the code "db->close()" == "delete db".
there are other ways to do so

2023-06-13 15:25 UTC, RoyBenMoshe commented on options/options_test.cc
> +  db1 = nullptr;
same as above

2023-06-13 15:42 UTC, RoyBenMoshe commented on options/options_test.cc
> +}
fixed

2023-06-13 17:40 UTC, RoyBenMoshe commented on options/options_test.cc
> +
fixed

2023-06-13 18:47 UTC, RoyBenMoshe commented on options/options_test.cc
> +  ASSERT_OK(DestroyDB("db1", op1));
fixed

2023-06-13 19:09 UTC, RoyBenMoshe commented on options/options.cc
> +      new WriteBufferManager(initial_write_buffer_size_, cache));
Yes, I understand and have considered it, but from my point of view - this is a very "wide" feature and we offer basic level configuration in it. These changes to the defaults may have a minor or major positive or negative effect on the proposed configuration. Hopefully we can identify major impacts caused by changing the default values ​​and consider the best decision for the product then.

2023-06-13 19:20 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  s = db3->DropColumnFamily(cf);
As I wrote before, this is a simple way to make sure that this software can be run repeatedly several times

2023-06-13 20:07 UTC, RoyBenMoshe commented on options/options_test.cc
> +
fixed

2023-06-14 02:32 UTC, mrambacher submitted a review, later dismissed

2023-06-14 02:32 UTC, mrambacher commented on examples/enable_speedb_features_example.cc
> +  Status s = DB::Open(op1, kDBPath1, &db1);
Above it looks as if only kDBPath is defined on Windows?  Or did I miss it?

2023-06-14 02:32 UTC, mrambacher commented on include/rocksdb/options.h
> +  // memtable_factory we will initialize and configure those.
This comment is a little off.  I think it should say more like this method will set values such as ...

However, that is a bit dangerous, since that could change in a future release as new things are marked in this list and the comment would need to be updated.

2023-06-14 02:32 UTC, mrambacher commented on include/rocksdb/options.h
> +  // the function might overide any of those.
override

2023-06-14 02:32 UTC, mrambacher commented on include/rocksdb/options.h
> +  // write buffer size by 512 * 1024 * 1024ul using
I do not think this comment belongs here and would be better in a Wiki about this feature.

2023-06-14 02:32 UTC, mrambacher commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
Should the sharedOptions be a const & ?

2023-06-14 02:32 UTC, mrambacher commented on options/options.cc
> +  std::shared_ptr<rocksdb::MemoryAllocator> memory_allocator = nullptr;
The memory allocator is something that should be in SharedOptions and not assumed as null

2023-06-14 02:32 UTC, mrambacher commented on options/options_test.cc
> +  ASSERT_TRUE(db3->GetOptions().delayed_write_rate == so.GetDelayedWriteRate());
Why not ASSERT_EQ rather than true?  Won't EQ give more information?

2023-06-14 02:52 UTC, udi-speedb commented on include/rocksdb/options.h
> +  // memtable_factory we will initialize and configure those.
> This comment is a little off. I think it should say more like this method will set values such as ...
> 
> However, that is a bit dangerous, since that could change in a future release as new things are marked in this list and the comment would need to be updated.

Do you propose to avoid listing them altogether?
I agree that having a list of members in a comment risks being out of date.
Nevertheless, I believe a user must be aware of which options not to change.
How would a user know which options not to modify when using this feature?
Are they expected to carefully go over the code and see for themselves?

2023-06-14 03:10 UTC, udi-speedb commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
> Should the sharedOptions be a const & ?

Although technically this is possible (would compile), I believe that it **shouldn't** be const.
The called code copies the shared pointers to non const shared pointers that may (and are modified).

2023-06-14 03:11 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  s = db3->DropColumnFamily(cf);
OK

2023-06-14 03:12 UTC, udi-speedb commented on options/options_test.cc
> +              3 * 512 * 1024 * 1024ul);
I do not understand the reply

2023-06-14 03:19 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  delete db1;
Since this is an exmple for users rather than a unit test, I suggest calling Close() and checking the return status to emphasize the proper way for a user to behave in production code

2023-06-14 03:25 UTC, udi-speedb commented on options/options.cc
> +      new WriteBufferManager(initial_write_buffer_size_, cache));
I am not saying you need to change the defaults. 
All I am saying is that by having them explicitly you minimize the risk of misconfiguration (now or in the future).
What are the disadvantages in my way? I haven't understood them.

2023-06-14 03:33 UTC, mrambacher commented on include/rocksdb/options.h
> +  // memtable_factory we will initialize and configure those.
The OptimizeForSmallDB and IncreaseParallelism do not say which values they change.  There is also a push to do "InitializeForDbBench/DbStress" and those will not likely say which options they will change either.

The point is that Speedb should set the options it chooses.  The user is still free to change whatever they want after.

2023-06-14 03:34 UTC, mrambacher commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
> > Should the sharedOptions be a const & ?
> 
> Although technically this is possible (would compile), I believe that it **shouldn't** be const. The called code copies the contained / internal shared pointers to non const shared pointers that may (and are modified).

Copying the contents is done all of the time through a const.  Look at DB::Open as one example.  The const tells the user that the value they pass in is not changing, which is the case here.

2023-06-14 04:01 UTC, udi-speedb commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
A const object implies that the object along with its state (the cumulative stats of all of its members, recursively) will not change (in the deep copy meaning of it).
On some platforms, a const object may be placed in ROM.
The fact that you are passing it as const, then copy its members to non const variables, and later access them to modify the objects in the original const object (e.g., the wbm, cache, etc.) is a violation of this principle. It doesn't matter that it compiles.

2023-06-14 08:07 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  delete db1;
fixed

2023-06-14 08:08 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  Status s = DB::Open(op1, kDBPath1, &db1);
missed it, fixed

2023-06-14 12:24 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +  // the function might overide any of those.
fixed

2023-06-14 14:48 UTC, RoyBenMoshe commented on include/rocksdb/options.h
> +};
changed

2023-06-14 19:53 UTC, mrambacher commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
I would argue const is the correct semantics for this SharedOptions parameter -- the called function should not be changing the value of this parameter.  If it does, there are race conditions for threads (what if the same object is used in two threads at the same time).  There is also the potential that the object is modified when used twice -- what would the expected semantics be of op1.Setup(shared); op2.Setup(shared) -- would you expect that the second call would change the values in op1 based on shared being updated?

2023-06-15 02:06 UTC, udi-speedb commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
All I am saying is that the had SharedOptions been written as follows:
```
class SharedOptions {
    public:
        std::shared_ptr<Cache>& Cache() const {return cache_;}        
    private:
        std::shared_ptr<Cache> cache_;
};
void Options::EnableSpeedb(const SharedOptions& so) {
   ...
   block_cache = so.Cache();
   ...
``` 
It wouldn't compile, unless you change Cache() to return a const std::shared_ptr<Cache>.
As it is, cache_ is a public struct member, so no need to have a Cache() accessor to copy it, but it is conceptually the same.

2023-06-16 12:27 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  return 0;
You still need to delete the db-s after closing them.

2023-06-16 16:28 UTC, mrambacher commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
> All I am saying is that the had SharedOptions been written as follows:
> 
> ```
> class SharedOptions {
>     public:
>         std::shared_ptr<Cache>& Cache() const {return cache_;}        
>     private:
>         std::shared_ptr<Cache> cache_;
> };
> void Options::EnableSpeedb(const SharedOptions& so) {
>    ...
>    block_cache = so.Cache();
>    ...
> ```
> 
> It wouldn't compile, unless you changed Cache() to return a const std::shared_ptr. As it is, cache_ is a public struct member, so no need to have a Cache() accessor to copy it, but it is conceptually the same.

But that should return a const shared_ptr!  That is just good code hygiene.  Typical C++ code would define two methods (if necessary -- a const one which returns a const& and a non-const one which returns a &.

In reality, the code you describe ends up making a "copy" (taking another reference) anyway

2023-06-17 05:42 UTC, hilikspdb commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SpeedbSharedOptions& shared_options) {
Shared ptr can not be returned from const object (even if it const) assignment  and copy require changing the content of the source. The only option i know that exists is..
  
 std::shared_ptr<Cache>& Cache()  {return cache_;}  
Cache *Cache() const {return cache_.get();}

2023-06-25 09:10 UTC, RoyBenMoshe commented on examples/enable_speedb_features_example.cc
> +  return 0;
fixed

2023-06-25 13:04 UTC, udi-speedb approved these changes

2023-07-12 14:11 UTC, ayulas approved these changes

2023-07-12 15:14 UTC, mrambacher commented on options/options.cc
> +Options* Options::EnableSpeedbFeatures(SharedOptions& shared_options) {
This should be a const &

2023-07-12 15:14 UTC, mrambacher commented on options/options.cc
> +DBOptions* DBOptions::EnableSpeedbFeaturesDB(SharedOptions& shared_options) {
This should be a const &

2023-07-12 15:14 UTC, mrambacher commented on options/options_test.cc
> +  ASSERT_TRUE(so.GetTotalRamSizeBytes() == total_ram_size_bytes);
These would be better as ASSERT_EQ

2023-07-24 12:37 UTC, Yuval-Ariel commented
on hold until https://github.com/speedb-io/speedb/pull/610 is pushed

2023-07-24 16:03 UTC, ayulas approved these changes

2023-08-07 14:51 UTC, ayulas commented on tools/db_bench_tool.cc
> -    "\ttable-readers-mem    -- Print table readers memory. excluding memory "
why it is related?

2023-08-07 14:55 UTC, ayulas commented on options/options.cc
> +    if (total_ram_size_bytes_ / 4 > increase_by) {
pls calc the increase size on a local parameter, and just call SetBufferSize once with the correct value

2023-08-14 04:38 UTC, merged