570 spdb memtable use seek parralel threshold mishandled
speedb-io/speedb pull request #603
Opened 2023-07-10 09:36 UTC by ayulas

2023-07-16 07:22 UTC, Yuval-Ariel commented on plugin/speedb/memtable/hash_spd_rep.cc
> +         {0, OptionType::kSizeT, OptionVerificationType::kNormal,
offset should be offsetof(struct HashSpdbRepOptions, hash_bucket_count)

2023-07-16 07:22 UTC, Yuval-Ariel commented on plugin/speedb/memtable/hash_spd_rep.cc
> +         {0, OptionType::kBoolean, OptionVerificationType::kNormal,
same here, 
offset should be offsetof(struct HashSpdbRepOptions, use_seek_parralel_threshold)

2023-07-16 07:23 UTC, Yuval-Ariel commented on plugin/speedb/memtable/hash_spd_rep.cc
> +
remove space

2023-07-16 11:37 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +         {0, OptionType::kBoolean, OptionVerificationType::kNormal,
done

2023-07-16 11:37 UTC, ayulas commented on plugin/speedb/memtable/hash_spd_rep.cc
> +         {0, OptionType::kSizeT, OptionVerificationType::kNormal,
done

2023-07-16 11:55 UTC, Yuval-Ariel approved these changes

2023-07-17 12:31 UTC, ayulas commented
done :-)

2023-07-17 13:14 UTC, mrambacher commented on plugin/speedb/memtable/hash_spd_rep.cc
> +        {"use_seek_parralel_threshold",
parallel is the proper English spelling

2023-07-17 13:14 UTC, mrambacher requested changes
"Parallel", not "parralel" please "-)

2023-07-18 06:13 UTC, merged