Support Non-Blocking Manual Compactions (CompactRange) (#597)
speedb-io/speedb pull request #656
Opened 2023-08-29 13:33 UTC by udi-speedb

Add a new option to CompactRangeOptions, a callback object. By defaut, the callback is empty so CompactRange() will be blocking (as it is now). If the callback is set, the callback object's callback method will be called upon completion with the completion status.

2023-08-29 15:28 UTC, ofriedma commented
@udi-speedb please add example file how to use the new non blocking compaction feature

2023-08-29 15:51 UTC, ofriedma commented
please use port::Thread and not std::thread for spawning threads, so the on thread start callback will work on those threads

2023-08-30 04:45 UTC, udi-speedb commented
> please use port::Thread and not std::thread for spawning threads, so the on thread start callback will work on those threads

Done. Please just note that I have made the ThreadWithCb::joinable() a const method (same as std::thread::joinable()) (I am calling this method from a const method of mine).

2023-08-30 08:31 UTC, udi-speedb commented
> @udi-speedb please add example file how to use the new non blocking compaction feature

Done

2023-08-30 14:19 UTC, ofriedma commented
@udi-speedb add a unit test for closing the db before compact range has been completed

2023-08-31 08:53 UTC, udi-speedb commented
> @udi-speedb add a unit test for closing the db before compact range has been completed

As we have discussed, it will be the user's responsibility to wait for all non-blocking CompactRange() calls to have their respective callbacks called. Thereafter, the Close() shouldn't have any issues joining the internal threads.
I will add a note about that in the CompactRange()'s documentation.

2023-09-04 09:36 UTC, ofriedma requested changes

2023-09-04 09:36 UTC, ofriedma commented on db/db_impl/compact_range_threads_mngr.cc
> +void CompactRangeThreadsMngr::CleanupCompletedThreads() {
I think joinable() will always return true, because we have never called join().

2023-09-04 09:36 UTC, ofriedma commented on db/db_impl/db_impl.cc
> +  compact_range_threads_mngr_.Shutdown();
great

2023-09-04 09:36 UTC, ofriedma commented on db/db_impl/db_impl.h
> +
maybe add a small comment here about the manual/range compaction thread manager

2023-09-04 09:36 UTC, ofriedma commented on db_stress_tool/db_stress_test_base.cc
> +              "Time: %d\n",
Maybe print the status message?

2023-09-04 09:36 UTC, ofriedma commented on include/rocksdb/options.h
> +  std::shared_ptr<CompactRangeCompletedCbIf> async_completion_cb;
async_completion_cb, maybe use another name, what if we will want to add Async PUT for example?

2023-09-04 09:36 UTC, ofriedma commented on include/rocksdb/port_defs.h
> +  bool joinable() const { return thread_.joinable(); }
Thank you

2023-09-04 09:40 UTC, ofriedma commented on java/src/test/java/org/rocksdb/CompactRangeCompletedCbTest.java
Add license here

2023-09-04 10:44 UTC, udi-speedb commented on db/db_compaction_test.cc
> +class DBCompactionTestWithParamWithMCC
Manual Compaction Control

2023-09-04 10:56 UTC, udi-speedb commented on db/db_compaction_test.cc
> +void DefaultCompletionStatusValidation(Status completion_status,
I have removed in new code that I have added, however, there are many places in the db_compaction_test.cc that use "ROCKSDB_NAMESPACE::" which I will not touch to avoid unnecessary code changes that are irrelevant to this PR.

2023-09-04 10:59 UTC, udi-speedb commented on db_stress_tool/db_stress_test_base.cc
> +              "Time: %d\n",
This is std::future::future_status which is an enum, what status message should I print?

2023-09-05 12:18 UTC, ofriedma approved these changes
before merge please add comments

2023-09-05 12:18 UTC, ofriedma commented on db/db_compaction_test.cc
> +class DBCompactionTestWithMCC : public DBCompactionTest,
Please add a note what is MCC.

2023-09-05 12:18 UTC, ofriedma commented on db/db_impl/db_impl.h
> +
please notice

2023-09-05 14:18 UTC, udi-speedb commented on java/src/test/java/org/rocksdb/CompactRangeCompletedCbTest.java
I have removed this file

2023-09-05 14:18 UTC, udi-speedb commented on db/db_compaction_test.cc
> +class DBCompactionTestWithMCC : public DBCompactionTest,
Done

2023-09-06 09:50 UTC, ofriedma approved these changes

2023-09-18 12:22 UTC, merged