Support running enabled speedb feature check in CI
speedb-io/speedb pull request #726
Opened 2023-10-18 14:03 UTC by ayulas

2023-10-18 16:03 UTC, ayulas commented on include/rocksdb/options.h
> -  DBOptions* EnableSpeedbFeaturesDB(SharedOptions& shared_options);
@ofriedma is my reviewer I didn’t assign nyou  and I already discussed it with him 
It was as part of support multi dbs that was broken but I decided not handle it now 
It will be reverted

2023-10-29 10:16 UTC, udi-speedb commented
@ayulas - Could you please describe what issues you have found and how they were found? Thanks

2023-10-30 19:07 UTC, udi-speedb commented
@ayulas - Please describe what's the status of this pr.

2023-11-09 12:56 UTC, ayulas commented
@ofriedma pls approve

2023-11-09 14:19 UTC, ofriedma commented on HISTORY.md
> +* Enable speedb features:::support in CI (#723).
Maybe a better name for the PR is Support enable speedb features in db_stress

2023-11-09 14:29 UTC, ofriedma requested changes
Beside other comments there is a gap I'm currently working on in the db_bench, which enable speedb features is overriding other flags the user explicitly write, so there could be other tests running defacto although the user didn't mean to.
To avoid duplicate both PRs, I'm suggesting after I will find all those conflicts in the db_bench code, to complete/resume this PR.
@ayulas please tell me what you think

2023-11-09 14:29 UTC, ofriedma commented on HISTORY.md
> +* Enable speedb features:::support in CI (#723).
Maybe a better name for the PR is Support enable speedb features in db_stress

2023-11-09 14:29 UTC, ofriedma commented on db_stress_tool/db_stress_common.h
> +DECLARE_uint64(speedb_features_ram_size);
The name in db_bench_tool is total_ram_size.
There are more flags max_background_jobs, enable_speedb_features and delayed_write_rate maybe we should add them too.

2023-11-09 14:29 UTC, ofriedma commented on db_stress_tool/db_stress_test_base.cc
> +      if (FLAGS_speedb_features_ram_size) {
it means that every db_stress by default, it will enable speedb features other than db_bench.

2023-11-09 14:35 UTC, ayulas commented on HISTORY.md
> +* Enable speedb features:::support in CI (#723).
Ok

2023-11-09 14:36 UTC, ayulas commented on db_stress_tool/db_stress_common.h
> +DECLARE_uint64(speedb_features_ram_size);
The decision was to only use the ram with 3 options 0 - means the enable Speedb is false and other option ram size . I didn’t decide it this what I was told to

2023-11-09 14:37 UTC, ayulas commented on db_stress_tool/db_stress_test_base.cc
> +      if (FLAGS_speedb_features_ram_size) {
No .. look at the crash test py

2023-11-12 16:42 UTC, ofriedma approved these changes

2023-11-12 21:28 UTC, merged