Enable speedb features: Constrain the i/f of SharedOptions (make immutable)
speedb-io/speedb pull request #742
Opened 2023-11-03 05:48 UTC by udi-speedb

2023-11-05 10:17 UTC, ofriedma requested changes

2023-11-05 10:17 UTC, ofriedma commented on examples/enable_speedb_features_example.cc
> +  // NOT Having a prefix-extractor (the deafult) will result in the
having

2023-11-05 10:17 UTC, ofriedma commented on options/options.cc
> +    allow_concurrent_memtable_write = false;
Assert for a configuration conflict

2023-11-05 19:01 UTC, udi-speedb commented on examples/enable_speedb_features_example.cc
> +  // NOT Having a prefix-extractor (the deafult) will result in the
Done

2023-11-06 16:09 UTC, ofriedma approved these changes

2023-11-07 02:36 UTC, udi-speedb commented
@ofriedma - Please resolve the comments. Thanks

2023-11-07 10:00 UTC, ofriedma commented on options/options.cc
> +    allow_concurrent_memtable_write = false;
where is the assert? @udi-speedb

2023-11-07 10:28 UTC, merged