fix conflicts between db_bench flags and enable speedb features flag
speedb-io/speedb pull request #765
Opened 2023-11-12 15:08 UTC by ofriedma

2023-11-13 10:35 UTC, udi-speedb commented
What about HISTORY.md?

2023-11-13 10:35 UTC, udi-speedb requested changes

2023-11-13 10:35 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +void ValidateEnableSpeedbFlags() {
What about:
- pinning_policy
- filter_policy
- db_write_buffer_size
- bytes_per_sync

2023-11-13 10:35 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +void ValidateEnableSpeedbFlags() {
This is very verbose and error prone. In addition, it should probably be more or less duplicated in db_stress (anywhere else).
In view of that, I think we should strive to do the following:
- Have the validation code in some common location that may be used by both db_bench & db_stress
- Maybe have the validation use some list of flag names (strings). The code will go over the list and validate that all of the flags are in their default values. That will make the code shorter, somewhat more generic, and easier to maintain.

2023-11-13 10:35 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +    ErrorExit("total_ram_size configured without enabling speedb features");
If use_blob_cache, blob_cache will be set to cache_. Is that OK?

2023-11-13 10:35 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +  ValidateEnableSpeedbFlags();
An issue that needs consideration is related to the ValidateXXXX() methods.
They are using the flags to perform their validations (*e.g., ValidatePinningRelatedOptions()). However, the EnableSpeedbFeatures will run later and reconfigure the entities, regardless of the values of the flags. That means the validation may actually be meaningless.

2023-11-13 13:02 UTC, ofriedma commented on tools/db_bench_tool.cc
> +    if (FLAGS_cache_type != "lru_cache") {
let's keep it as !is_default

2023-11-13 13:03 UTC, ofriedma commented on tools/db_bench_tool.cc
> +    if (FLAGS_prefix_size && FLAGS_memtablerep != "skip_list") {
will remove it

2023-11-13 13:05 UTC, ofriedma commented on tools/db_bench_tool.cc
> +    ErrorExit("total_ram_size configured without enabling speedb features");
AFAIK blob cache is not being set with enable speedb features

2023-11-13 13:11 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +    ErrorExit("total_ram_size configured without enabling speedb features");
It is not. However, currently db_bench shares the single cache_ with blobs. With enable feature, it will use db_bench's cache_ while enable will define a separate cache to be used as the block cache

2023-11-13 16:29 UTC, ofriedma commented on tools/db_bench_tool.cc
> +void ValidateEnableSpeedbFlags() {
max_num_parallel_flushes , should be too?

2023-11-15 06:28 UTC, udi-speedb requested changes

2023-11-15 06:28 UTC, udi-speedb commented on HISTORY.md
> +* fix conflicts between db_bench flags and enable speedb features flag
Please add the issue number and also place it at the end, to reflect the order in which items were actually added

2023-11-15 06:28 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +      "whole_key_filtering", "optimize_filters_for_hits"};
What about use_blob_cache?

2023-11-15 06:28 UTC, udi-speedb commented on tools/db_bench_tool.cc
> +void ValidateEnableSpeedbFlags() {
The short anser is yes.
Better include it as well. EnableSpeedbFeatures is not calculating it, but also not accepting it as a parameter to use from the user. So, if the user explicitly set it in db_bench, it will have no affect.
And please also include start_delay_percent for the same reasons.

2023-11-19 08:13 UTC, udi-speedb approved these changes

2023-11-19 08:13 UTC, udi-speedb commented on HISTORY.md
> +* fix conflicts between db_bench flags and enable speedb features flag(#743).
Please move to the end to reflect the order in which updates were made.

2023-11-19 08:14 UTC, udi-speedb commented
@ofriedma - Before we merge, please ask @erez-speedb to test the branch, use db_bench, etc. Thanks

2023-12-25 15:30 UTC, ofriedma commented
@udi-speedb please review, no conflicts were after rebase

2023-12-31 09:08 UTC, udi-speedb approved these changes

2024-01-03 09:25 UTC, ofriedma commented
@udi-speedb please look at all conversation resolv them it is ok and tell me if it does not

2024-01-03 09:25 UTC, merged