Fix cross-compilation on macOS x86_64 CPUs with target CPU arm64
speedb-io/speedb pull request #823
Opened 2024-01-27 19:17 UTC by shpala

Fix cross-compilation on macOS x86_64 CPUs with target CPU arm64 by manually setting CMAKE_SYSTEM_PROCESSOR to the cross-compilation target whenever CMAKE_SYSTEM_PROCESSOR doesn't match CMAKE_OSX_ARCHITECTURES after project() call. This is probably a Cmake bug that happens on macOS. (#822).

The issue happens when SpeeDB is built using the follwoing command:
`cmake -G "Unix Makefiles" -DCMAKE_SYSTEM_PROCESSOR=arm64 ..`
The build itself succeeds, but because Cmake wrongly sets CMAKE_SYSTEM_PROCESSOR to x86_64 instead of arm64 and causes crc32c_arm64.cc not to be compiled.
This in turn makes the project fails any linking with SpeeDB:
```
Undefined symbols for architecture arm64:
"crc32c_arm64(unsigned int, unsigned char const*, unsigned long)", referenced from:
speedb::crc32c::ExtendARMImpl(unsigned int, char const*, unsigned long) in libspeedb.a(crc32c.cc.o)
```

2024-01-28 12:31 UTC, ofriedma requested changes

2024-01-28 12:31 UTC, ofriedma commented on CMakeLists.txt
> +  # because projec() might reset CMAKE_SYSTEM_PROCESSOR back to the value of CMAKE_HOST_SYSTEM_PROCESSOR.
should be project().
Please update the HISTORY.md file with this change.
other than those LGTM

2024-02-01 08:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/speedb-io/speedb?pullRequest=823) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/speedb-io/speedb?pullRequest=823) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Pavel Ferencz<br/>:x: ofriedma<br/><hr/>**Pavel Ferencz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/speedb-io/speedb?pullRequest=823) it.</sub>

2024-02-18 01:24 UTC, jhult commented
@shpala, any updates on this? I think there are just 2 small changes required (and the CLA).

2024-02-23 11:39 UTC, shpala commented
Done

2024-02-28 12:20 UTC, ofriedma approved these changes

2024-02-29 09:03 UTC, ofriedma commented
Compilation succeed for linux arm

2024-02-29 09:03 UTC, merged

2024-02-29 09:03 UTC, ofriedma commented
@shpala Merged, Thank you for your contribution