Devops ci/implement sanity to ci
speedb-io/speedb pull request #84
Opened 2022-07-28 14:34 UTC by nathan-bo

2022-08-22 06:37 UTC, maxb-io approved these changes

2022-09-05 12:57 UTC, isaac-io requested changes

2022-09-05 12:57 UTC, isaac-io commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/sanity_check.yml@main
Can we not pin to `main` and use the [local repository syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow)?

2022-09-05 13:55 UTC, nathan-bo commented on .github/workflows/ci_pipeline.yml
> +    uses: speedb-io/speedb/.github/workflows/sanity_check.yml@main
yep, done

2022-09-05 13:57 UTC, isaac-io approved these changes

2022-09-05 13:59 UTC, isaac-io commented
The wrong sanity job now seems to be required for merging after these changes. @maxb-io can you set the right one?

2022-11-16 09:28 UTC, closed without merging